# SPDX-License-Identifier: Apache-2.0
encryption:
  existingSecret: homarr-encryption

externalSecrets:
  enabled: true
  secretStoreRef:
    name: homarr-ci-fake-store
    kind: SecretStore
  data:
    - secretKey: secret-encryption-key
      remoteRef:
        key: homarr/secret-encryption-key
    - secretKey: auth-secret
      remoteRef:
        key: homarr/auth-secret

extraManifests:
  - apiVersion: external-secrets.io/v1
    kind: SecretStore
    metadata:
      name: homarr-ci-fake-store
    spec:
      provider:
        fake:
          data:
            - key: homarr/secret-encryption-key
              value: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
            - key: homarr/auth-secret
              value: "helmforge-homarr-auth-secret"
