# SPDX-License-Identifier: Apache-2.0
# PostgreSQL subchart
postgresql:
  enabled: true
  auth:
    database: homarr
    username: homarr
    password: testpassword

startupProbe:
  initialDelaySeconds: 0
  periodSeconds: 2
  timeoutSeconds: 5

readinessProbe:
  periodSeconds: 2
  timeoutSeconds: 5
