# SPDX-License-Identifier: Apache-2.0
# CI: Gateway API HTTPRoute
gatewayAPI:
  enabled: true
  parentRefs:
    - name: public-gateway
      namespace: gateway-system
  hostnames:
    - deals.example.com
discountBandit:
  appUrl: https://deals.example.com
