# SPDX-License-Identifier: Apache-2.0
# CI: NetworkPolicy with crawler and database egress
networkPolicy:
  enabled: true
  egress:
    enabled: true
    allowDNS: true
    allowHTTPS: true
    allowHTTP: true
    allowSameNamespaceDatabase: true
