# SPDX-License-Identifier: Apache-2.0
bundled-elasticsearch:
  fullnameOverride: kibana-ci-elasticsearch

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
