# SPDX-License-Identifier: Apache-2.0
bundled-elasticsearch:
  fullnameOverride: kibana-ci-elasticsearch

encryptionKeys:
  requireForMultipleReplicas: true

externalSecrets:
  enabled: true
  skipCRDCheck: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: xpack-security-encryption-key
      remoteRef:
        key: test/kibana-security-encryption-key
    - secretKey: xpack-reporting-encryption-key
      remoteRef:
        key: test/kibana-reporting-encryption-key
    - secretKey: xpack-encrypted-saved-objects-encryption-key
      remoteRef:
        key: test/kibana-saved-objects-encryption-key
  dataFrom: []
