# SPDX-License-Identifier: Apache-2.0
bundled-elasticsearch:
  fullnameOverride: kibana-ci-elasticsearch

gateway:
  enabled: true
  skipCRDCheck: true
  hostnames:
    - kibana.example.com
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
