# SPDX-License-Identifier: Apache-2.0
elasticsearch:
  hosts:
    - http://elasticsearch:9200

encryptionKeys:
  securityKey: "01234567890123456789012345678901"
  reportingKey: "abcdefghijklmnopqrstuvwxyz123456"
  encryptedSavedObjectsKey: "savedobjects01234567890123456789"

waitForElasticsearch:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 768Mi
  limits:
    cpu: "1"
    memory: 1Gi

startupProbe:
  initialDelaySeconds: 180
  failureThreshold: 90

readinessProbe:
  failureThreshold: 20

extraConfig:
  xpack.securitySolution.enabled: false
  xpack.screenshotting.browser.chromium.disableSandbox: true
