# SPDX-License-Identifier: Apache-2.0
bundled-elasticsearch:
  fullnameOverride: kibana-ci-elasticsearch

networkPolicy:
  enabled: true
  ingress:
    allowSameNamespace: true
  egress:
    enabled: true
    allowDns: true
    elasticsearch:
      enabled: true
      ports:
        - 9200
