# SPDX-License-Identifier: Apache-2.0
fullnameOverride: ryot-external
postgresql:
  enabled: false
database:
  host: fixture-postgresql
  name: ryot
  username: ryot
  passwordSecret: fixture-postgresql-auth
  passwordKey: user-password
  caSecret: fixture-postgresql-tls
networkPolicy:
  extraEgress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
              app.kubernetes.io/instance: fixture-postgresql
      ports:
        - protocol: TCP
          port: 5432
