# SPDX-License-Identifier: Apache-2.0
webodm:
  host: webodm.local

processing:
  resources:
    requests: {cpu: "2", memory: 4Gi, ephemeral-storage: 5Gi}
    limits: {cpu: "8", memory: 16Gi, ephemeral-storage: 40Gi}
