# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: qdrant
description: Qdrant vector database
type: application
version: 1.0.0
appVersion: "1.18.2"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - qdrant
  - kubernetes
  - helm
home: https://helmforge.dev/docs/charts/qdrant
sources:
  - https://github.com/helmforgedev/charts/tree/main/charts/qdrant
  - https://github.com/qdrant/qdrant
icon: https://helmforge.dev/icons/charts/qdrant.png
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "initial qdrant chart"
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: berlofa@helmforge.dev
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/links: |
    - name: Official Website
      url: https://github.com/qdrant/qdrant
    - name: Documentation
      url: https://helmforge.dev/docs/charts/qdrant
    - name: Source
      url: https://github.com/qdrant/qdrant
    - name: support
      url: https://github.com/helmforgedev/charts/issues
