# SPDX-License-Identifier: Apache-2.0
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
image:
  repository: docker.io/qdrant/qdrant
  tag: "v1.18.2"
  pullPolicy: IfNotPresent
imagePullSecrets: []
replicaCount: 1
app:
  port: 6333
  command: []
  args: []
  env:
    - name: QDRANT__SERVICE__HTTP_PORT
      value: "6333"
  extraEnv: []
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  existingClaim: ""
  mountPath: /qdrant/storage
serviceAccount:
  create: false
  name: ""
  annotations: {}
  automountServiceAccountToken: false
service:
  type: ClusterIP
  port: 6333
  annotations: {}
  ipFamilyPolicy: ""
  ipFamilies: []
ingress:
  enabled: false
  ingressClassName: traefik
  annotations: {}
  hosts: []
  tls: []
gateway:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []
  path: /
  pathType: PathPrefix
probes:
  startup: { enabled: true, initialDelaySeconds: 5, periodSeconds: 10, timeoutSeconds: 3, failureThreshold: 60 }
  liveness: { enabled: true, initialDelaySeconds: 0, periodSeconds: 20, timeoutSeconds: 5, failureThreshold: 3 }
  readiness: { enabled: true, initialDelaySeconds: 0, periodSeconds: 10, timeoutSeconds: 5, failureThreshold: 6 }
resources: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""
terminationGracePeriodSeconds: 30
podLabels: {}
podAnnotations: {}
extraVolumes: []
extraVolumeMounts: []
extraManifests: []
