# SPDX-License-Identifier: Apache-2.0
fullnameOverride: affine-metrics
metrics:
  enabled: true
  ingressFrom:
    - podSelector:
        matchLabels:
          app: affine-monitor
  serviceMonitor:
    enabled: true
    interval: 5s
    scrapeTimeout: 3s
  prometheusRule:
    enabled: true
persistence:
  size: 1Gi
postgresql:
  standalone:
    persistence:
      size: 2Gi
redis:
  standalone:
    persistence:
      size: 1Gi
