# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
persistence:
  enabled: false
postgresql:
  standalone:
    persistence:
      enabled: false

auth:
  existingSecret: flowise-auth-credentials

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: encryption-key
      remoteRef:
        key: test/token
    - secretKey: jwt-auth-token-secret
      remoteRef:
        key: test/token
    - secretKey: jwt-refresh-token-secret
      remoteRef:
        key: test/token
    - secretKey: express-session-secret
      remoteRef:
        key: test/token
    - secretKey: token-hash-secret
      remoteRef:
        key: test/token
