# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
persistence:
  enabled: false
postgresql:
  standalone:
    persistence:
      enabled: false

auth:
  existingSecret: flowise-auth-credentials

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: encryption-key
      remoteRef:
        key: flowise/auth
        property: encryptionKey
