# SPDX-License-Identifier: Apache-2.0
# Staging - 1 master + 2 data, persistent storage, basic monitoring
clusterProfile: staging

clusterName: staging-cluster

master:
  persistence:
    size: 20Gi
    storageClass: standard

data:
  persistence:
    size: 100Gi
    storageClass: standard

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
