# SPDX-License-Identifier: Apache-2.0
# CI scenario: External Secrets Operator (GR-061).
# rcon.existingSecret is required when externalSecrets.enabled=true and rcon.enabled=true.
persistence:
  enabled: false

rcon:
  enabled: true
  existingSecret: my-minecraft-rcon-secret

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: rcon-password
      remoteRef:
        key: minecraft/credentials
        property: rcon-password
