# SPDX-License-Identifier: Apache-2.0
sonarqube:
  databaseMode: external

database:
  external:
    jdbcUrl: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/sonarqube
    username: sonar
    password: change-me
