# SPDX-License-Identifier: Apache-2.0
sonarqube:
  databaseMode: embedded
  webJavaOpts: "-Xms128m -Xmx384m"
  ceJavaOpts: "-Xms128m -Xmx384m"
  searchJavaOpts: "-Xms384m -Xmx384m"

persistence:
  data:
    enabled: false
  extensions:
    enabled: false
  logs:
    enabled: false

resources:
  requests:
    cpu: 250m
    memory: 1536Mi
  limits:
    cpu: 2
    memory: 2304Mi
