{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "webodm.fullname" . }}-worker
  labels:
    {{- include "webodm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "webodm.componentSelectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
{{- end }}
