{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.webodm.existingSecret }}
{{- $name := include "webodm.secretName" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "webodm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.webodm.existingSecretKeyKey }}: {{ if .Values.webodm.secretKey }}{{ .Values.webodm.secretKey | b64enc }}{{ else if and $existing (hasKey $existing.data .Values.webodm.existingSecretKeyKey) }}{{ index $existing.data .Values.webodm.existingSecretKeyKey }}{{ else }}{{ randAlphaNum 64 | b64enc }}{{ end }}
  {{ .Values.webodm.existingSecretProcessorTokenKey }}: {{ if .Values.webodm.processorToken }}{{ .Values.webodm.processorToken | b64enc }}{{ else if and $existing (hasKey $existing.data .Values.webodm.existingSecretProcessorTokenKey) }}{{ index $existing.data .Values.webodm.existingSecretProcessorTokenKey }}{{ else }}{{ randAlphaNum 48 | b64enc }}{{ end }}
{{- end }}
