# SPDX-License-Identifier: Apache-2.0
# CI scenario: External Secrets Operator v1 integration.

auth:
  enabled: true
  existingSecret: memcached-auth

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Merge
  data:
    - secretKey: token
      remoteRef:
        key: test/token

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: memcached-auth
    type: Opaque
    stringData:
      authfile: app:helmforge-test-password
