# SPDX-License-Identifier: Apache-2.0
# CI scenario: Gateway API TCPRoute rendering.

gateway:
  tcpRoute:
    enabled: true
    parentRefs:
      - name: internal-tcp-gateway
        namespace: gateway-system
        sectionName: memcached

