# SPDX-License-Identifier: Apache-2.0
# CI scenario: production-oriented distributed cache nodes.

architecture: distributed
replicaCount: 3

memcached:
  memoryLimitMB: 256
  maxConnections: 4096
  threads: 4
  maxItemSize: 2m
  disableFlushAll: true
  disableDumping: true

tls:
  enabled: true
  existingSecret: memcached-tls
  caKey: ca.crt
  verifyMode: "0"
  minVersion: "2"

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: memcached-tls
    type: kubernetes.io/tls
    stringData:
      tls.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDkDCCAnigAwIBAgIUWqx1J/t2WPHTK7x11aaAUZC5X8AwDQYJKoZIhvcNAQEL
        BQAwFDESMBAGA1UEAwwJbWVtY2FjaGVkMB4XDTI2MDYxNDExNTkzNVoXDTI3MDYx
        NDExNTkzNVowFDESMBAGA1UEAwwJbWVtY2FjaGVkMIIBIjANBgkqhkiG9w0BAQEF
        AAOCAQ8AMIIBCgKCAQEAxcpYgpCMvwZY0mEP+T5rPytmrfDCJ80K/mAjOVvgOmhp
        fHyS9AWZoGE/KmpvC8R+X8QltAxZhjxAC5q+IfnJ7jy36UFcYmbRtsd9RhU3eX2W
        4tnhox0eJxP6jX07tmf2RyNlqs8cQmdxYhjbNYCtMCcJh0OvYOpNgGc5vK6BvH32
        gNYVFBEphm4z0yMypw3YauKnKr13cu/1kBG5FkhYNfj/azqZgbhwCq6zJ+nbsEm0
        gguJfDev3d12g9A91CBTlIsampEgg28x5Bmc3aCFtMqWv8CCL25BeM0SHUpQcimU
        roUm9fgTBfKJnkx5XpIEzJFKiszJhMUee74k6kR+9QIDAQABo4HZMIHWMB0GA1Ud
        DgQWBBSf/lo4Fxc4c6xt9AGdRxfRfl59fDAfBgNVHSMEGDAWgBSf/lo4Fxc4c6xt
        9AGdRxfRfl59fDAPBgNVHRMBAf8EBTADAQH/MIGCBgNVHREEezB5gkJtZW1jYWNo
        ZWQtY2ktcHJvZHVjdGlvbi12YWx1ZXMtbWVtY2FjaGVkLmhmLXZhbGlkYXRlLW1l
        bWNhY2hlZC5zdmOCKG1lbWNhY2hlZC1jaS1wcm9kdWN0aW9uLXZhbHVlcy1tZW1j
        YWNoZWSCCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAOMZD2NWjPbg1xDlG
        S217Zn+yRXdHQedjy13WQaUQDkPDJh0izAQ1Q1URBY+dW9w1AdK+xBQEI9qBog9i
        yRaWTKPW5YpviTm3/+DNlMol+sTjVX9O4jnwW2y9PZj/Voi1xNHO+taeWeXUNb5W
        vL07bjTmTSaWDuO6ymDRsjbdenlUUuQplCC7P0Y3bS1QDCA5t05MiWAfzFWKMy6d
        VWv/DyIxzzgvme6UEk12ijPe19P/ViKM//MrMpA72MNySpisnTtmuubOdKRk5sCg
        UmT9k7DABXZ5O6Q7ByRneMdbQBJvwckreny3Sap6y4DHmLsan7X01cJOgPmcO2Vp
        WlEkjA==
        -----END CERTIFICATE-----
      tls.key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFyliCkIy/BljS
        YQ/5Pms/K2at8MInzQr+YCM5W+A6aGl8fJL0BZmgYT8qam8LxH5fxCW0DFmGPEAL
        mr4h+cnuPLfpQVxiZtG2x31GFTd5fZbi2eGjHR4nE/qNfTu2Z/ZHI2WqzxxCZ3Fi
        GNs1gK0wJwmHQ69g6k2AZzm8roG8ffaA1hUUESmGbjPTIzKnDdhq4qcqvXdy7/WQ
        EbkWSFg1+P9rOpmBuHAKrrMn6duwSbSCC4l8N6/d3XaD0D3UIFOUixqakSCDbzHk
        GZzdoIW0ypa/wIIvbkF4zRIdSlByKZSuhSb1+BMF8omeTHlekgTMkUqKzMmExR57
        viTqRH71AgMBAAECggEAWwmwxZ/s+HveZC8C4DEHwhKi90rKwvEQr1bmv573TUsD
        yqW4KhNty7EXFtnYdO0jUccBp6bLigqvW+gEvbSwajSOXhGUiUJUIrIdiiV33Daf
        PZkVzzM2zrvWZkuPMX0WkVXMlNsxYaslOAbC1xR8Ip7FNvpDffM6avCYVa1oz63H
        E06/hd0wnaBZdvNKtgrTUr4T44Dfx6IWGQ+mbqkF+ChSem9b5Xq5pxZDeanOw/qT
        bahsvjcNnmuhUklv2mAwou4TNFunn4XZbpL+sKOC7Y9qD4Wc/D+1T/PsIInQ33l9
        r8eXDl6ksCnPb9ffexl0b992mZpQYXIeG2XmAmRXfQKBgQDyQybTIQBOkuIG2TtS
        GaOE//YXLHWFNFBL89p1S3+Fbk507eLkLjAbX//P+h8et/4i+PbJIwCJtbE+ZEgb
        uORuP8Nl+XX9XaxoyWibFB8+kYVYlKDs07Ah6xqf2KpV8D8bjktI/n/lopHC4+xw
        byykUXiNscel1JK5KWapw90G8wKBgQDRAZvq/5yO/SVxpc4Y+jOEE0mWfTfNX9Du
        C50mw99Zn3ZgaAaH1tUzpZEASeoROABqayIFZiRv+EfJPLpY+5HkGX6o59OWIbeb
        6MLEboSQ3oaRX0bSSQYRgKJUW3ACKyDWWXmEtFEsEOAAzh73B02vohOiGOQxwLDR
        GzZc13msdwKBgGNMHue+yQ9rqPVBqMzX8WwcNdP9xxWYAamAA/S7w0L/mWzX7H22
        aMVvrbyjOoouxB21igGbNSc8r69xDxU9zXNa804i17fH41j35MZbkwrkPpG2Kdeo
        VLMyWDFYb0jWNienRThgCDApWDFXlpvnFZcsRYteaQSRgqoeTBQdUcT9AoGACTdy
        8rf25W9QWWSgZAWUg/x9wD8hWNMi2Xx1n6H/lWosxC+SKidVG4Pvkv2vbrbzfb3f
        sDFC5hUixUMCTK47Tr25EiW29OXjvOJUxGjDO8g0UvDKpLdHpznu7p1hoRbZydoE
        O8/fzHuqBR8Ryn7t9BLHntxOI8uFgJMcoJd37B0CgYEA6gI0p/ZE8IzfpV6STZnf
        cbifsfFlWMGKSXBJug9Yevx+MPXPyg1i3Z0Mg1v6pVs226qKybwQqYOo4c0ohDGO
        9aClgQfhRp+D6WLDDjVW9+kF3ACDr6jsjM6Za4ziIM2xA3D9YGcJMFh49bUuwprC
        6xgCLvADDsX7KQ0Gl5D0qxQ=
        -----END PRIVATE KEY-----
      ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIDkDCCAnigAwIBAgIUWqx1J/t2WPHTK7x11aaAUZC5X8AwDQYJKoZIhvcNAQEL
        BQAwFDESMBAGA1UEAwwJbWVtY2FjaGVkMB4XDTI2MDYxNDExNTkzNVoXDTI3MDYx
        NDExNTkzNVowFDESMBAGA1UEAwwJbWVtY2FjaGVkMIIBIjANBgkqhkiG9w0BAQEF
        AAOCAQ8AMIIBCgKCAQEAxcpYgpCMvwZY0mEP+T5rPytmrfDCJ80K/mAjOVvgOmhp
        fHyS9AWZoGE/KmpvC8R+X8QltAxZhjxAC5q+IfnJ7jy36UFcYmbRtsd9RhU3eX2W
        4tnhox0eJxP6jX07tmf2RyNlqs8cQmdxYhjbNYCtMCcJh0OvYOpNgGc5vK6BvH32
        gNYVFBEphm4z0yMypw3YauKnKr13cu/1kBG5FkhYNfj/azqZgbhwCq6zJ+nbsEm0
        gguJfDev3d12g9A91CBTlIsampEgg28x5Bmc3aCFtMqWv8CCL25BeM0SHUpQcimU
        roUm9fgTBfKJnkx5XpIEzJFKiszJhMUee74k6kR+9QIDAQABo4HZMIHWMB0GA1Ud
        DgQWBBSf/lo4Fxc4c6xt9AGdRxfRfl59fDAfBgNVHSMEGDAWgBSf/lo4Fxc4c6xt
        9AGdRxfRfl59fDAPBgNVHRMBAf8EBTADAQH/MIGCBgNVHREEezB5gkJtZW1jYWNo
        ZWQtY2ktcHJvZHVjdGlvbi12YWx1ZXMtbWVtY2FjaGVkLmhmLXZhbGlkYXRlLW1l
        bWNhY2hlZC5zdmOCKG1lbWNhY2hlZC1jaS1wcm9kdWN0aW9uLXZhbHVlcy1tZW1j
        YWNoZWSCCWxvY2FsaG9zdDANBgkqhkiG9w0BAQsFAAOCAQEAOMZD2NWjPbg1xDlG
        S217Zn+yRXdHQedjy13WQaUQDkPDJh0izAQ1Q1URBY+dW9w1AdK+xBQEI9qBog9i
        yRaWTKPW5YpviTm3/+DNlMol+sTjVX9O4jnwW2y9PZj/Voi1xNHO+taeWeXUNb5W
        vL07bjTmTSaWDuO6ymDRsjbdenlUUuQplCC7P0Y3bS1QDCA5t05MiWAfzFWKMy6d
        VWv/DyIxzzgvme6UEk12ijPe19P/ViKM//MrMpA72MNySpisnTtmuubOdKRk5sCg
        UmT9k7DABXZ5O6Q7ByRneMdbQBJvwckreny3Sap6y4DHmLsan7X01cJOgPmcO2Vp
        WlEkjA==
        -----END CERTIFICATE-----

serviceAccount:
  create: true
  automountServiceAccountToken: false

networkPolicy:
  enabled: true
  metrics:
    enabled: true
    allowSameNamespace: true
  egress:
    enabled: true
    allowDNS: true

metrics:
  enabled: true
  memcachedTLS:
    enabled: true
    serverName: memcached-ci-production-values-memcached.hf-validate-memcached.svc

pdb:
  enabled: true
  minAvailable: 2

resources:
  requests:
    cpu: 100m
    memory: 320Mi
  limits:
    memory: 320Mi

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: memcached
