# SPDX-License-Identifier: Apache-2.0
# CI scenario: SASL flag rendering with an externally prepared SASL Secret.

auth:
  enabled: true
  mode: sasl
  existingSecret: memcached-sasl
  sasl:
    configKey: memcached.conf
    databaseKey: memcachedsasldb

memcached:
  protocol: binary
