# SPDX-License-Identifier: Apache-2.0
service:
  type: NodePort
  nodePorts:
    nat: 31115
    rendezvous: 31116
    rendezvousUdp: 31116
    relay: 31117
server:
  relayServers:
    - rustdesk.example.com:31117
networkPolicy:
  ingressFrom:
    - ipBlock:
        cidr: 192.0.2.0/24
