# SPDX-License-Identifier: Apache-2.0
fullnameOverride: twenty
bootstrap:
  password: Owned%Runtime:@/#+?fixture-2026
postgresql:
  standalone:
    persistence:
      size: 2Gi
redis:
  standalone:
    persistence:
      size: 1Gi
