# SPDX-License-Identifier: Apache-2.0
fullnameOverride: twenty-eso
bootstrap:
  existingSecret: twenty-eso-user
  passwordKey: password
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: twenty-eso-user
      spec:
        target:
          template:
            engineVersion: v2
            data:
              password: '{{ .password | sha256sum | trunc 32 }}'
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
