# SPDX-License-Identifier: Apache-2.0
webodm:
  host: webodm.example.com

web:
  terminationGracePeriodSeconds: 30

worker:
  terminationGracePeriodSeconds: 60

postgresql:
  standalone:
    persistence:
      enabled: false

redis:
  standalone:
    persistence:
      enabled: false

persistence:
  retain: false

processing:
  terminationGracePeriodSeconds: 60
  persistence:
    retain: false
