# SPDX-License-Identifier: Apache-2.0
webodm:
  existingSecret: webodm-auth

web:
  terminationGracePeriodSeconds: 30

worker:
  terminationGracePeriodSeconds: 60

postgresql:
  standalone:
    persistence:
      enabled: false

redis:
  standalone:
    persistence:
      enabled: false

persistence:
  retain: false

processing:
  terminationGracePeriodSeconds: 60
  persistence:
    retain: false

externalSecrets:
  enabled: true
  items:
    - fullnameOverride: webodm-auth
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          creationPolicy: Owner
        data:
          - secretKey: secret-key
            remoteRef: {key: test/password}
          - secretKey: processor-token
            remoteRef: {key: test/token}
