{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "notediscovery.validate" . }}
{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notediscovery.configName" . }}
  labels:
    {{- include "notediscovery.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    app:
      name: {{ .Values.notediscovery.appName | quote }}
    server:
      host: "0.0.0.0"
      port: {{ .Values.app.port }}
      reload: false
      allowed_origins:
        {{- toYaml .Values.notediscovery.allowedOrigins | nindent 8 }}
      debug: {{ .Values.notediscovery.debug }}
    storage:
      notes_dir: {{ .Values.persistence.mountPath | quote }}
      plugins_dir: "./plugins"
    search:
      enabled: {{ .Values.notediscovery.searchEnabled }}
    ui:
      autosave_delay_ms: {{ .Values.notediscovery.autosaveDelayMs }}
    authentication:
      enabled: true
      secret_key: {{ .Values.auth.secretKey | quote }}
      password: {{ .Values.auth.password | quote }}
      session_max_age: {{ .Values.auth.sessionMaxAge }}
      api_key: {{ .Values.auth.apiKey | quote }}
{{- end }}
