# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: rabbitmq-auth

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: rabbitmq-auth
    type: Opaque
    stringData:
      rabbitmq-username: user
      rabbitmq-password: ci-password
      rabbitmq-erlang-cookie: ci-erlang-cookie
