# SPDX-License-Identifier: Apache-2.0
# Test with ConfigMaps for live-reload configuration
configMaps:
  sitemaps:
    enabled: true
    files:
      myhome.sitemap: |
        sitemap myhome label="My Home" {
          Frame label="Overview" {
            Text item=gTemperature label="Temperature [%.1f C]"
          }
        }
  things:
    enabled: true
    files:
      network.things: |
        Thing network:pingdevice:router [ hostname="192.168.1.1", retry=1, timeout=5000, refreshInterval=60000 ]
  items:
    enabled: true
    files:
      myhome.items: |
        Number gTemperature "Temperature" <temperature>
