# SPDX-License-Identifier: Apache-2.0
moodle:
  wwwroot: https://learn.example.com
  sslProxy: true
  existingSecret: learning-admin
  adminEmail: learning-admin@example.com
persistence:
  size: 50Gi
sessions:
  enabled: true
redis:
  enabled: true
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: learn.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: learning-tls
      hosts:
        - learn.example.com
