# SPDX-License-Identifier: Apache-2.0
# CI: monitoring enabled with ServiceMonitor
tunnel:
  quickTunnel:
    enabled: true

serviceMonitor:
  enabled: true
  interval: 15s
  labels:
    release: prometheus

service:
  annotations:
    prometheus.io/scrape: "true"
