{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled=true" .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "mongodb.fullname" . }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
