# SPDX-License-Identifier: Apache-2.0
# Managed PostgreSQL, S3, and SMTP.
database:
  mode: external
  external:
    host: ente-rw.database.svc.cluster.local
    name: ente
    username: ente
    existingSecret: ente-postgresql
    sslMode: verify-full
postgresql:
  enabled: false
storage:
  s3:
    endpoint: https://objects.ente.test
    region: eu-central-1
    bucket: ente-photos
    existingSecret: ente-s3
smtp:
  enabled: true
  host: smtp.ente.test
  email: ente@ente.test
  existingSecret: ente-smtp
