# SPDX-License-Identifier: Apache-2.0
# Secret material sourced from an existing ClusterSecretStore.
museum:
  existingSecret: ente-museum
storage:
  s3:
    existingSecret: ente-s3
externalSecrets:
  enabled: true
  items:
    - name: museum
      spec:
        secretStoreRef:
          name: production
          kind: ClusterSecretStore
        target:
          name: ente-museum
        dataFrom:
          - extract:
              key: ente/museum
    - name: s3
      spec:
        secretStoreRef:
          name: production
          kind: ClusterSecretStore
        target:
          name: ente-s3
        dataFrom:
          - extract:
              key: ente/s3
