# SPDX-License-Identifier: Apache-2.0
# HA application topology. Use external HA PostgreSQL for full-stack HA.
productionMode: true
museum:
  externalUrl: https://api.ente.test
  existingSecret: ente-museum
  api:
    replicaCount: 3
    skipBackgroundJobs: true
  worker:
    enabled: true
storage:
  s3:
    endpoint: https://objects.ente.test
    bucket: ente-photos
    existingSecret: ente-s3
web:
  replicaCount: 3
pdb:
  museum:
    enabled: true
  web:
    enabled: true
networkPolicy:
  enabled: true
