{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "zookeeper.validate" . }}
{{- if .Values.externalSecrets.enabled }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ include "zookeeper.namespace" . | quote }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ include "zookeeper.externalSecretTargetName" . }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy | quote }}
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}
