# SPDX-License-Identifier: Apache-2.0
phpmyadmin:
  host: mysql.default.svc.cluster.local

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  auth:
    enabled: true
    usernameRemoteRef:
      key: test/username
    passwordRemoteRef:
      key: test/password
