# SPDX-License-Identifier: Apache-2.0
externalSecrets:
  enabled: true
  items:
    - name: test-secret
      storeRef:
        name: test-store
        kind: ClusterSecretStore
      data:
        - secretKey: key
          remoteRef:
            key: remote-key
