# SPDX-License-Identifier: Apache-2.0
# CI: ntfy 2.26.3 abuse ban-feed on the writable data volume
ntfy:
  banFeed:
    enabled: true
    file: /var/cache/ntfy/ban.log
    window: 10m
    threshold: 1
    weights:
      - "404*:1"
      - "*:0"
