# SPDX-License-Identifier: Apache-2.0
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hoppscotch.fullname" . }}
  labels: {{ include "hoppscotch.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled=true" .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "hoppscotch.fullname" . }}
    creationPolicy: Owner
  {{- with .Values.externalSecrets.data }}
  data: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.dataFrom }}
  dataFrom: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
