apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-proxy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy-gateway.labels" . | nindent 4 }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        {{- $mode := include "envoy-gateway.proxy.mode" . }}
        {{- if eq $mode "DaemonSet" }}
        replicas: null
        {{- else }}
        replicas: {{ include "envoy-gateway.proxy.replicaCount" . }}
        {{- end }}
        pod:
          securityContext:
            {{- toYaml .Values.proxy.podSecurityContext | nindent 12 }}
      envoyService:
        type: {{ .Values.proxy.service.type }}
        {{- with .Values.proxy.service.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- if .Values.monitoring.enabled }}
  telemetry:
    {{- if .Values.monitoring.accessLogs.enabled }}
    accessLog:
      settings:
      - format:
          type: {{ .Values.monitoring.accessLogs.format | upper }}
        sinks:
        - type: File
          file:
            path: /dev/stdout
    {{- end }}
    metrics:
      prometheus:
        disable: false
  {{- end }}
