{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.gatewayClass.create }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-proxy-config
  namespace: {{ include "envoy-gateway.namespace" . }}
  labels:
    {{- include "envoy-gateway.labels" . | nindent 4 }}
spec:
  {{- with .Values.proxy.ipFamily }}
  ipFamily: {{ . }}
  {{- end }}
  provider:
    type: Kubernetes
    kubernetes:
      {{- $podSpec := include "envoy-gateway.proxy.podSpec" . | trim }}
      {{- if eq .Values.proxy.kind "DaemonSet" }}
      envoyDaemonSet:
        {{- if $podSpec }}
        pod:
          {{- $podSpec | nindent 10 }}
        {{- end }}
        container:
          image: {{ printf "%s:%s" .Values.proxy.image.repository .Values.proxy.image.tag }}
          resources:
            {{- include "envoy-gateway.proxy.resources" . | nindent 12 }}
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                  - name: shutdown-manager
                    image: {{ printf "%s:%s" .Values.proxy.shutdownManager.image.repository .Values.proxy.shutdownManager.image.tag }}
                    imagePullPolicy: {{ .Values.proxy.shutdownManager.image.pullPolicy }}
      {{- else }}
      envoyDeployment:
        replicas: {{ .Values.proxy.replicaCount }}
        {{- if $podSpec }}
        pod:
          {{- $podSpec | nindent 10 }}
        {{- end }}
        container:
          image: {{ printf "%s:%s" .Values.proxy.image.repository .Values.proxy.image.tag }}
          resources:
            {{- include "envoy-gateway.proxy.resources" . | nindent 12 }}
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                  - name: shutdown-manager
                    image: {{ printf "%s:%s" .Values.proxy.shutdownManager.image.repository .Values.proxy.shutdownManager.image.tag }}
                    imagePullPolicy: {{ .Values.proxy.shutdownManager.image.pullPolicy }}
      {{- if .Values.proxy.autoscaling.enabled }}
      envoyHpa:
        minReplicas: {{ .Values.proxy.autoscaling.minReplicas }}
        maxReplicas: {{ .Values.proxy.autoscaling.maxReplicas }}
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: {{ .Values.proxy.autoscaling.targetCPUUtilizationPercentage }}
      {{- end }}
      {{- end }}
      envoyService:
        type: {{ .Values.proxy.service.type }}
        {{- with .Values.proxy.service.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}


  {{- if .Values.monitoring.enabled }}
  telemetry:
    {{- if .Values.monitoring.accessLogs.enabled }}
    accessLog:
      settings:
      - format:
          {{- if eq (lower .Values.monitoring.accessLogs.format) "json" }}
          type: JSON
          json:
            start_time: "%START_TIME%"
            method: "%REQ(:METHOD)%"
            path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            protocol: "%PROTOCOL%"
            response_code: "%RESPONSE_CODE%"
            response_flags: "%RESPONSE_FLAGS%"
            bytes_received: "%BYTES_RECEIVED%"
            bytes_sent: "%BYTES_SENT%"
            duration: "%DURATION%"
            upstream_host: "%UPSTREAM_HOST%"
          {{- else }}
          type: Text
          text: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%UPSTREAM_HOST%"'
          {{- end }}
        sinks:
        - type: File
          file:
            path: /dev/stdout
    {{- end }}
    metrics:
      prometheus:
        disable: false
  {{- end }}
  shutdown:
    drainTimeout: 60s
    minDrainDuration: 5s
{{- end }}
