{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-controller
  labels:
    {{- include "envoy-gateway.controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "envoy-gateway.controller.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-proxy
  labels:
    {{- include "envoy-gateway.proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "envoy-gateway.proxy.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: admin
    interval: 30s
    path: /stats/prometheus
{{- end }}
