apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-gateway.fullname" . }}-proxy
  labels:
    {{- include "envoy-gateway.proxy.labels" . | nindent 4 }}
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
  - name: http
    port: {{ .Values.proxy.service.httpPort }}
    targetPort: 8080
    protocol: TCP
  - name: https
    port: {{ .Values.proxy.service.httpsPort }}
    targetPort: 8443
    protocol: TCP
  selector:
    {{- include "envoy-gateway.proxy.selectorLabels" . | nindent 4 }}
