# SPDX-License-Identifier: Apache-2.0
gatewayAPI:
  enabled: true
  httpRoutes:
    - name: moodle-route
      hostnames: [learn.example.com]
ingress:
  enabled: true
  ingressClassName: test
  hosts:
    - host: learn.example.com
      paths:
        - path: /
          pathType: Prefix
