# SPDX-License-Identifier: Apache-2.0
database:
  type: mariadb
  prefix: edu_
  connectTimeout: 600
postgresql:
  enabled: false
mariadb:
  enabled: true
  fullnameOverride: moodle-bundled-mariadb
metrics:
  enabled: true
networkPolicy:
  enabled: true
