# SPDX-License-Identifier: Apache-2.0
database:
  type: mysql
  prefix: learn_
  connectTimeout: 600
postgresql:
  enabled: false
mysql:
  enabled: true
  fullnameOverride: moodle-bundled-mysql
metrics:
  enabled: true
networkPolicy:
  enabled: true
