# SPDX-License-Identifier: Apache-2.0
# External Secrets Operator example. The chart renders ExternalSecret resources,
# but it does not install ESO or create SecretStore/ClusterSecretStore objects.

postgresql:
  enabled: false

database:
  external:
    host: postgres-primary.database.svc.cluster.local
    name: umami
    username: umami

externalSecrets:
  enabled: true
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  app:
    enabled: true
    appSecretRemoteRef:
      key: prod/umami
      property: app-secret
  database:
    enabled: true
    passwordRemoteRef:
      key: prod/umami
      property: database-password
