{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.database.dsn (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memos.databaseSecretName" . }}
  labels:
    {{- include "memos.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.existingSecretKey }}: {{ .Values.database.dsn | quote }}
{{- end }}
