# SPDX-License-Identifier: Apache-2.0
# CI: dev profile (default - single node, minimal resources)
clusterProfile: dev

master:
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 2Gi

sysctlInit:
  enabled: false
