# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
master:
  persistence:
    enabled: false

data:
  persistence:
    enabled: false

security:
  existingCredentialsSecret: elastic-credentials-secret

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: elastic-password
      remoteRef:
        key: elasticsearch/auth
        property: password
