# SPDX-License-Identifier: Apache-2.0
# CI: staging profile - 1 master + 2 data nodes
clusterProfile: staging

master:
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 2Gi

data:
  persistence:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 4Gi

sysctlInit:
  enabled: false
