{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and (not (include "immich.databaseInternalEnabled" .)) (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-database
  labels:
    {{- include "immich.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ include "immich.databasePassword" . | quote }}
{{- end }}
{{- if and (not (include "immich.valkeyInternalEnabled" .)) (not .Values.valkey.external.existingSecret) .Values.valkey.external.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-redis
  labels:
    {{- include "immich.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.valkey.external.password | quote }}
{{- end }}
