# SPDX-License-Identifier: Apache-2.0
fullnameOverride: memos-external-mysql
persistence:
  size: 1Gi
database:
  driver: mysql
  host: fixture-mysql
  passwordSecret: fixture-mysql-auth
  passwordKey: mysql-user-password
  caSecret: fixture-mysql-tls
  networkPolicyPeers:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: fixture-mysql
