# SPDX-License-Identifier: Apache-2.0
fullnameOverride: memos-external-postgresql
persistence:
  size: 1Gi
database:
  driver: postgres
  host: fixture-postgresql
  passwordSecret: fixture-postgresql-auth
  passwordKey: user-password
  caSecret: fixture-postgresql-tls
  networkPolicyPeers:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: fixture-postgresql
