# SPDX-License-Identifier: Apache-2.0
fullnameOverride: memos-eso
bootstrap:
  existingSecret: memos-eso-bootstrap
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: memos-eso-bootstrap
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
