# SPDX-License-Identifier: Apache-2.0
provisioning:
  existingSecret: memos-provisioning

memos:
  instanceUrl: http://memos.local

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: memos-provisioning
    type: Opaque
    stringData:
      memos-instance-setting-general.json: |
        {
          "key": "GENERAL",
          "generalSetting": {
            "disallowUserRegistration": false,
            "disallowPasswordAuth": false,
            "weekStartDayOffset": 1
          }
        }
