# SPDX-License-Identifier: Apache-2.0
persistence:
  enabled: false
auth:
  client:
    enabled: true
externalSecrets:
  enabled: true
  secretStoreRef:
    name: zookeeper-ci-fake-store
    kind: SecretStore
  data:
    - secretKey: jaas.conf
      remoteRef:
        key: zookeeper/jaas
extraManifests:
  - apiVersion: external-secrets.io/v1
    kind: SecretStore
    metadata:
      name: zookeeper-ci-fake-store
    spec:
      provider:
        fake:
          data:
            - key: zookeeper/jaas
              value: |
                Server {
                  org.apache.zookeeper.server.auth.DigestLoginModule required
                  user_client="helmforge-test-password";
                };
