# SPDX-License-Identifier: Apache-2.0
fullnameOverride: mssql-dual
license:
  acceptEULA: true
service:
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
initdb:
  databases:
    - name: acceptance
