# SPDX-License-Identifier: Apache-2.0
fullnameOverride: mssql-existing
license:
  acceptEULA: true
auth:
  existingSecret: mssql-existing-auth
tls:
  existingSecret: mssql-existing-tls
initdb:
  databases:
    - name: acceptance
    - name: application
      username: application
      existingSecret: mssql-app-auth
  scriptsConfigMaps:
    - mssql-app-scripts
