# SPDX-License-Identifier: Apache-2.0
fullnameOverride: mssql-metrics
license:
  acceptEULA: true
service:
  port: 1444
initdb:
  databases:
    - name: acceptance
metrics:
  enabled: true
  secretKey: connection
  ingressFrom:
    - podSelector:
        matchLabels:
          app: mssql-monitor
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
