{{- include "gophish.validateAll" . }}
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophish.backupSecretName" . }}
  labels:
    {{- include "gophish.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  {{ .Values.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
