{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "gophish.validateAll" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophish.fullname" . }}-phish
  labels:
    {{- include "gophish.labels" . | nindent 4 }}
    app.kubernetes.io/component: phish
  {{- with .Values.phishService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.phishService.type }}
  {{- $ipFamilyPolicy := coalesce .Values.phishService.ipFamilyPolicy .Values.service.ipFamilyPolicy }}
  {{- with $ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- $ipFamilies := default .Values.service.ipFamilies .Values.phishService.ipFamilies }}
  {{- with $ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: phish
      port: {{ .Values.phishService.port }}
      targetPort: phish
      protocol: TCP
  selector:
    {{- include "gophish.selectorLabels" . | nindent 4 }}
