# SPDX-License-Identifier: Apache-2.0
persistence:
  enabled: false
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: jenkins.example.local
      paths:
        - path: /
          pathType: Prefix
