# SPDX-License-Identifier: Apache-2.0
# Merge with your production routing, administrator Secret and storage values.
database:
  type: mysql
postgresql:
  enabled: false
mysql:
  enabled: true
mariadb:
  enabled: false
