# SPDX-License-Identifier: Apache-2.0
fullnameOverride: bentopdf
replicaCount: 2
podDisruptionBudget:
  enabled: true
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: bentopdf
