{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if eq (include "elasticsearch.security.enabled" .) "true" -}}
{{- if and .Values.security.generatePasswords (not .Values.security.existingCredentialsSecret) -}}
{{- $existing := lookup "v1" "Secret" (include "elasticsearch.namespace" .) (include "elasticsearch.credentialsSecretName" .) -}}
{{- $data := dict -}}
{{- if $existing -}}
{{- $data = get $existing "data" | default dict -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.credentialsSecretName" . }}
  namespace: {{ (include "elasticsearch.namespace" .) }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
data:
  elastic-password: {{ if hasKey $data "elastic-password" }}{{ get $data "elastic-password" | quote }}{{ else }}{{ randAlphaNum 24 | b64enc | quote }}{{ end }}
  kibana-system-password: {{ if hasKey $data "kibana-system-password" }}{{ get $data "kibana-system-password" | quote }}{{ else }}{{ randAlphaNum 24 | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}
