apiVersion: v2
name: automatisch
description: Open-source business automation platform — self-hosted Zapier alternative with PostgreSQL and Redis
icon: https://helmforge.dev/icons/charts/automatisch.png
type: application
version: 1.0.1
appVersion: "0.15.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - automation
  - workflow
  - zapier
  - automatisch
  - self-hosted
home: https://automatisch.io
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/automatisch/automatisch
annotations:
  helmforge.dev/maturity: alpha
  helmforge.dev/signed: cosign
  artifacthub.io/license: MIT
  artifacthub.io/category: integration-delivery
  artifacthub.io/prerelease: "true"
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/automatisch
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/automatisch
dependencies:
  - name: postgresql
    version: 1.8.4
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: redis
    version: 1.5.5
    repository: oci://ghcr.io/helmforgedev/helm
    condition: redis.enabled
