# SPDX-License-Identifier: Apache-2.0
postgresql:
  enabled: false
externalDatabase:
  host: nextcloud-external-db
  existingSecret: nextcloud-external-db
redis:
  enabled: false
externalRedis:
  host: nextcloud-external-redis
  existingSecret: nextcloud-external-redis
