# SPDX-License-Identifier: Apache-2.0
nextcloud:
  existingSecret: nextcloud-admin-eso
externalSecrets:
  enabled: true
  refreshInterval: 15s
  items:
    - fullnameOverride: nextcloud-admin-eso
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          template:
            data:
              admin-password: '{{ .password }}Aa1!'
        data:
          - secretKey: password
            remoteRef:
              key: test/password
