# SPDX-License-Identifier: Apache-2.0
nextcloud:
  trustedDomains: [cloud.example.com]
  overwriteCliUrl: http://cloud.example.com
gatewayAPI:
  enabled: true
  httpRoutes:
    - name: nextcloud-route
      hostnames: [cloud.example.com]
ingress:
  enabled: true
  ingressClassName: test
  hosts:
    - host: cloud.example.com
      paths:
        - path: /
          pathType: Prefix
