# SPDX-License-Identifier: Apache-2.0
postgresql:
  enabled: false
database:
  host: postgres.database.svc.cluster.local
  name: ryot
  username: ryot
  passwordSecret: ryot-postgresql-password
  caSecret: database-ca
  sslMode: verify-full
networkPolicy:
  extraEgress:
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: database}
          podSelector:
            matchLabels: {app.kubernetes.io/name: postgresql}
      ports:
        - {protocol: TCP, port: 5432}
