{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "certimate.fullname" . }}
  labels:
    {{- include "certimate.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- $paths := default (list (dict "path" "/" "pathType" "Prefix")) .paths }}
          {{- range $paths }}
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "certimate.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
