{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medikeep.appSecretName" . }}
  labels:
    {{- include "medikeep.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ include "medikeep.secretKey" . | quote }}
  {{- with .Values.secrets.adminDefaultPassword }}
  admin-password: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.ssoClientSecret }}
  sso-client-secret: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.postgresql.enabled) (not .Values.database.external.existingSecret) .Values.database.external.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medikeep.dbSecretName" . }}
  labels:
    {{- include "medikeep.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.external.password | quote }}
{{- end }}
