# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: helmforge-test-password
  standalone:
    persistence:
      enabled: false

rateLimiting:
  enabled: true
  externalRedis:
    host: "envoy-gateway-ci-external-secrets-redis-client"
    auth:
      enabled: true
      secretName: envoy-redis-credentials
      secretKey: redis-password

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: redis-password
      remoteRef:
        key: test/password
