# SPDX-License-Identifier: Apache-2.0
# CI: OliveTin 3000.18 custom PORT and dnsname argument validation
olivetin:
  port: 1447

config: |
  actions:
    - title: "Resolve host"
      shell: "getent hosts {{ hostname }}"
      arguments:
        - name: hostname
          title: "DNS hostname"
          type: dnsname
          default: "example.com"
