# SPDX-License-Identifier: Apache-2.0
replicaCount: 1
basicAuth:
  enabled: true
  existingSecret: apache-basicauth-managed
externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: htpasswd
      remoteRef:
        key: test/password
  dataFrom: []
