# SPDX-License-Identifier: Apache-2.0
replicaCount: 2
pdb:
  enabled: true
autoscaling:
  enabled: true
networkPolicy:
  enabled: true
basicAuth:
  enabled: true
  existingSecret: apache-basicauth
httpd:
  extraConfig: |
    Header always set X-Content-Type-Options "nosniff"
