# SPDX-License-Identifier: Apache-2.0
# Public ArchiveBox endpoint with TLS and explicit allowed hosts.

archivebox:
  adminUsername: admin
  existingSecret: archivebox-admin
  allowedHosts: archive.example.com
  publicIndex: "False"
  publicSnapshots: "False"
  publicAddLinks: "False"

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: archive.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - archive.example.com
      secretName: archivebox-tls

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "3"
    memory: 6Gi
