# SPDX-License-Identifier: Apache-2.0
# Simple self-contained alf.io deployment for local validation.

alfio:
  baseUrl: "http://localhost:8080"
  profiles: "dev"

postgresql:
  enabled: true
  auth:
    database: alfio
    username: alfio

resources:
  requests:
    cpu: 250m
    memory: 768Mi
  limits:
    cpu: "1"
    memory: 1536Mi

