# SPDX-License-Identifier: Apache-2.0
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
spec:
  {{- if ne (toString .Values.pdb.maxUnavailable) "" }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "memcached.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
{{- end }}
