# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.headlessServiceName" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  ports:
    - name: memcache
      port: {{ .Values.service.port }}
      targetPort: memcache
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  ports:
    - name: memcache
      port: {{ .Values.service.port }}
      targetPort: memcache
      protocol: TCP
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.metricsServiceName" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "memcached.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
