# SPDX-License-Identifier: Apache-2.0
{{- if .Values.gateway.tcpRoute.enabled }}
apiVersion: {{ .Values.gateway.tcpRoute.apiVersion }}
kind: TCPRoute
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "memcached.labels" . | nindent 4 }}
  {{- with .Values.gateway.tcpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gateway.tcpRoute.parentRefs | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "memcached.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
