# SPDX-License-Identifier: Apache-2.0
# Requires Prometheus Operator; match selectors to your actual monitoring Pods.
metrics:
  enabled: true
  ingressFrom:
    - podSelector:
        matchLabels:
          app: tei-monitor
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: true
