# SPDX-License-Identifier: Apache-2.0
# CI scenario: dual-stack for HTTP and SSH services (GR-058)
persistence:
  enabled: false

service:
  http:
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
  ssh:
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
