# SPDX-License-Identifier: Apache-2.0
# CI scenario: k3d-safe IP family policy coverage (GR-058)
persistence:
  enabled: false

service:
  http:
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
  ssh:
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
