backup:
  enabled: true
  suspend: true
  schedule: "0 3 * * *"
  archivePrefix: druid
  s3:
    endpoint: http://minio.minio.svc:9000
    bucket: druid-backups
    prefix: daily
    accessKey: minioadmin
    secretKey: minioadmin
