# External metadata storage scenario
postgresql:
  enabled: false

metadata:
  mode: external
  external:
    type: postgresql
    host: postgres.example.com
    port: 5432
    name: druid
    username: druid
    password: my-secret-password

zookeeperConfig:
  mode: external
  external:
    hosts: "zk1.example.com:2181,zk2.example.com:2181"

zookeeper:
  enabled: false
