# SPDX-License-Identifier: Apache-2.0
networkPolicy:
  enabled: true
  ingress:
    allowSameNamespace: true
    extraFrom:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: gateway-system
  egress:
    enabled: true
    allowDNS: true
    allowSameNamespace: true
    allowHTTPS: true
    allowHTTP: true
