# SPDX-License-Identifier: Apache-2.0
mysql:
  enabled: true
  auth:
    database: dolibarr
    username: dolibarr
    password: testpassword
    rootPassword: testrootpassword

backup:
  enabled: true
  suspend: true
  s3:
    endpoint: http://minio.minio.svc:9000
    bucket: dolibarr-backups
    prefix: dolibarr
    accessKey: minioadmin
    secretKey: minioadmin
