# SPDX-License-Identifier: Apache-2.0
mysql:
  enabled: false

database:
  mode: external
  external:
    host: mariadb.example.com
    port: 3306
    name: dolibarr
    username: dolibarr
    password: external-password
