# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
postgresql:
  enabled: false

database:
  mode: external
  external:
    host: "postgres-external"
    existingSecret: docmost-database-credentials

redis:
  enabled: false
  external:
    host: "redis-external"

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: database-password
      remoteRef:
        key: docmost/database
        property: password
