{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "opencut.fullname" . }}
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "opencut.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- else }}
    - ports:
        - protocol: TCP
          port: 3000
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress }}
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- else }}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: {{ include "opencut.databasePort" . }}
        - protocol: TCP
          port: {{ .Values.redisHttp.service.port }}
        - protocol: TCP
          port: 443
    {{- end }}
{{- if .Values.redisHttp.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "opencut.redisHttpName" . }}
  labels:
    {{- include "opencut.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-http
spec:
  podSelector:
    matchLabels:
      {{- include "opencut.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis-http
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "opencut.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: web
      ports:
        - protocol: TCP
          port: 80
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: {{ include "opencut.redisPort" . }}
{{- end }}
{{- end }}
