# SPDX-License-Identifier: Apache-2.0
# Expose Poznote via Gateway API HTTPRoute
# The chart auto-generates backendRefs pointing to the Poznote Service.
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: gateway-system
      hostnames:
        - notes.example.com
