# SPDX-License-Identifier: Apache-2.0
# Simple development deployment with defaults
persistence:
  data:
    enabled: true
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
