{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.auth.createSecret (not .Values.auth.existingSecret) (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.secretName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.keys.clientID }}: {{ .Values.auth.clientID | quote }}
  {{ .Values.auth.keys.clientSecret }}: {{ .Values.auth.clientSecret | quote }}
  {{ .Values.auth.keys.cookieSecret }}: {{ include "oauth2-proxy.cookieSecret" . | quote }}
{{- end }}
---
{{- if and .Values.authenticatedEmailsFile.enabled (not .Values.authenticatedEmailsFile.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.authenticatedEmailsSecretName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.authenticatedEmailsFile.secretKey }}: |-
    {{- range .Values.authenticatedEmailsFile.emails }}
    {{ . }}
    {{- end }}
{{- end }}
---
{{- if and .Values.alphaConfig.enabled (not .Values.alphaConfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-proxy.alphaConfigSecretName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  alpha-config.yaml: |
    {{- include "oauth2-proxy.alphaConfig" . | nindent 4 }}
{{- end }}
