# SPDX-License-Identifier: Apache-2.0
# Choose database encryption before first creation. Preserve all keys with backups.
database:
  encryptionSecret: papra-database-key
storage:
  encryptionSecret: papra-document-keys
