# SPDX-License-Identifier: Apache-2.0
architecture: replicaset

auth:
  enabled: true
  rootPassword: arbiter-ci-password
  replicaSetKey: 0123456789abcdef0123456789abcdef

replicaSet:
  name: rs0
  members: 2

arbiter:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 512Mi

persistence:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 1Gi
