{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.pdb.museum.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ente.fullname" . }}-museum-api
  labels:
    {{- include "ente.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.museum.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ente.componentLabels" (dict "root" . "component" "museum-api") | nindent 6 }}
{{- end }}
{{- if .Values.pdb.web.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ente.fullname" . }}-web
  labels:
    {{- include "ente.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.web.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "ente.componentLabels" (dict "root" . "component" "web") | nindent 6 }}
{{- end }}
