{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.museum.existingSecret }}
{{- $name := include "ente.museumSecretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.museum.secretKeys.encryptionKey }}: {{ if and $existing $existing.data (hasKey $existing.data .Values.museum.secretKeys.encryptionKey) }}{{ index $existing.data .Values.museum.secretKeys.encryptionKey }}{{ else }}{{ randBytes 32 | b64enc | quote }}{{ end }}
  {{ .Values.museum.secretKeys.hashKey }}: {{ if and $existing $existing.data (hasKey $existing.data .Values.museum.secretKeys.hashKey) }}{{ index $existing.data .Values.museum.secretKeys.hashKey }}{{ else }}{{ randBytes 64 | b64enc | quote }}{{ end }}
  {{ .Values.museum.secretKeys.jwtSecret }}: {{ if and $existing $existing.data (hasKey $existing.data .Values.museum.secretKeys.jwtSecret) }}{{ index $existing.data .Values.museum.secretKeys.jwtSecret }}{{ else }}{{ randBytes 32 | replace "+" "-" | replace "/" "_" | b64enc | quote }}{{ end }}
{{- end }}
{{- if not .Values.storage.s3.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.s3SecretName" . }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.storage.s3.existingSecretAccessKeyKey }}: {{ .Values.storage.s3.accessKey | quote }}
  {{ .Values.storage.s3.existingSecretSecretKeyKey }}: {{ .Values.storage.s3.secretKey | quote }}
{{- end }}
{{- if and (eq (include "ente.databaseMode" .) "external") (not .Values.database.external.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.databaseSecretName" . }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.external.existingSecretPasswordKey }}: {{ .Values.database.external.password | quote }}
{{- end }}
{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.smtpSecretName" . }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.smtp.existingSecretUsernameKey }}: {{ .Values.smtp.username | quote }}
  {{ .Values.smtp.existingSecretPasswordKey }}: {{ .Values.smtp.password | quote }}
{{- end }}
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ente.backupSecretName" . }}
  labels:
    {{- include "ente.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backup.s3.existingSecretAccessKeyKey }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.backup.s3.existingSecretSecretKeyKey }}: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
