# SPDX-License-Identifier: Apache-2.0
metrics:
  enabled: true
  existingSecret: moodle-monitoring
  ingressFrom:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  prometheusRule:
    enabled: true
    labels:
      release: kube-prometheus-stack
networkPolicy:
  enabled: true
