# SPDX-License-Identifier: Apache-2.0
fullnameOverride: papra-eso
auth:
  existingSecret: papra-eso-auth
bootstrap:
  existingSecret: papra-eso-bootstrap
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: papra-eso-auth
      spec:
        target:
          template:
            engineVersion: v2
            data:
              auth-secret: '{{ .password }}-fixture-session-signing-key'
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
    - fullnameOverride: papra-eso-bootstrap
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
