# SPDX-License-Identifier: Apache-2.0
fullnameOverride: papra
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: documents.example.test
      paths:
        - path: /
          pathType: Prefix
