# SPDX-License-Identifier: Apache-2.0
mysql:
  enabled: false
database:
  mode: external
  waitForConnection:
    enabled: false
  external:
    host: mysql.example.internal
    name: matomo
    username: matomo
    existingSecret: matomo-database
externalSecrets:
  enabled: true
  refreshInterval: 30m
  items:
    - fullnameOverride: matomo-database
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          name: matomo-database
          creationPolicy: Owner
        data:
          - secretKey: database-password
            remoteRef:
              key: test/password
startupProbe:
  enabled: false
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
