# SPDX-License-Identifier: Apache-2.0
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: matomo.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: matomo-tls
      hosts:
        - matomo.example.com
matomo:
  trustedHost: matomo.example.com
