# SPDX-License-Identifier: Apache-2.0
---
netbox:
  allowedHosts:
    - netbox.example.com
  metricsEnabled: true
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: netbox.example.com
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: shared-gateway
      hostnames:
        - netbox.example.com
metrics:
  serviceMonitor:
    enabled: true
networkPolicy:
  enabled: true
  egress:
    enabled: true
