{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.secrets.existingSecret }}
{{- if or .Values.secrets.oidcClientId .Values.secrets.oidcClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poznote.appSecretName" . }}
  labels:
    {{- include "poznote.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.oidcClientId }}
  oidc-client-id: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oidcClientSecret }}
  oidc-client-secret: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
