{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowise.authSecretName" . }}
  labels:
    {{- include "flowise.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ default (randAlphaNum 64) .Values.auth.encryptionKey | b64enc | quote }}
  jwt-auth-token-secret: {{ default (randAlphaNum 64) .Values.auth.jwtAuthTokenSecret | b64enc | quote }}
  jwt-refresh-token-secret: {{ default (randAlphaNum 64) .Values.auth.jwtRefreshTokenSecret | b64enc | quote }}
  express-session-secret: {{ default (randAlphaNum 64) .Values.auth.expressSessionSecret | b64enc | quote }}
  token-hash-secret: {{ default (randAlphaNum 64) .Values.auth.tokenHashSecret | b64enc | quote }}
---
{{- end }}
{{- if and (eq (include "flowise.databaseMode" .) "external") (not .Values.database.external.existingSecret) .Values.database.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowise.databaseSecretName" . }}
  labels:
    {{- include "flowise.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.external.password | b64enc | quote }}
---
{{- end }}
{{- if and (eq (include "flowise.redisMode" .) "external") (not .Values.redis.external.existingSecret) .Values.redis.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowise.redisSecretName" . }}
  labels:
    {{- include "flowise.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.external.password | b64enc | quote }}
---
{{- end }}
{{- if and (eq .Values.storage.type "s3") (not .Values.storage.s3.existingSecret) .Values.storage.s3.accessKeyId .Values.storage.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowise.storageSecretName" . }}
  labels:
    {{- include "flowise.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  secret-key: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
{{- end }}
