{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.web.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pimcore.fullname" . }}
  namespace: {{ include "pimcore.namespace" . | quote }}
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "pimcore.componentSelectorLabels" (dict "root" . "component" "web") | nindent 6 }}
{{- end }}
{{- if and .Values.podDisruptionBudget.enabled .Values.worker.enabled (gt (int .Values.worker.replicaCount) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pimcore.suffixedName" (dict "base" (include "pimcore.fullname" .) "suffix" "-worker") }}
  namespace: {{ include "pimcore.namespace" . | quote }}
  labels:
    {{- include "pimcore.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "pimcore.componentSelectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
{{- end }}
