# SPDX-License-Identifier: Apache-2.0
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: public
          namespace: gateway-system
      hostnames:
        - medikeep.example.com
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
