# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
persistence:
  enabled: false

mysql:
  enabled: false

database:
  external:
    existingSecret: ghost-db-credentials

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: ghost/db
        property: password
