# SPDX-License-Identifier: Apache-2.0
# CI values — external secrets enabled
# Uses the helmforge-fake-store provisioned in k3d by make prepare.
externalSecrets:
  enabled: true
  items:
    - name: db-creds
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: helmforge-fake-store
        target:
          name: booklore-db-creds
          creationPolicy: Owner
          template:
            data:
              password: '{{ index . "password" }}'
        data:
          - secretKey: password
            remoteRef:
              key: test/password
