apiVersion: v2
name: mongodb
description: MongoDB Helm Chart — standalone, replica set, or sharded cluster using the official MongoDB image
type: application
version: 1.7.1
appVersion: "8.2.6"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - mongodb
  - database
  - nosql
  - replicaset
  - sharded
home: https://helmforge.dev
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/mongo
icon: https://helmforge.dev/icons/charts/mongodb.png
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: update signing annotation to gpg+cosign and fix provenance upload
  artifacthub.io/maintainers: |
    - name: HelmForge
      email: helmforgedev@users.noreply.github.com
    - name: Maicon Berlofa
      email: maicon.berloffa@gmail.com
  artifacthub.io/alternativeName: "mongo"
  helmforge.dev/maturity: stable
  helmforge.dev/signed: gpg+cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: MIT
  artifacthub.io/category: database
  artifacthub.io/links: |
    - name: Official Website
      url: https://www.mongodb.com
    - name: Documentation
      url: https://helmforge.dev/docs/charts/mongodb
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/mongodb
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/images: |
    - name: mongodb
      image: docker.io/library/mongo:8.2.6
    - name: mongodb-exporter
      image: docker.io/percona/mongodb_exporter:0.49.0
    - name: backup-uploader
      image: docker.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/countly
