{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.live.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nautilus-trader.fullname" . }}
  labels:
    {{- include "nautilus-trader.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nautilus-trader.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: runner
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}

