# SPDX-License-Identifier: Apache-2.0
# CI: external database and cache
mariadb:
  enabled: true
  auth:
    rootPassword: test-password
database:
  mode: external
  external:
    host: appwrite-ci-external-db-values-mariadb
    port: 3306
    rootUser: root
    rootPassword: "test-password"
    name: appwrite

redis:
  enabled: true
  auth:
    password: test-redis-password
cache:
  mode: external
  external:
    host: appwrite-ci-external-db-values-redis-client
    port: 6379
    password: "test-redis-password"
