# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
appwrite:
  existingSecret: appwrite-credentials
  existingSecretOpenSslKey: appwrite-openssl-key
  existingSecretJwtKey: appwrite-jwt-secret

externalSecrets:
  enabled: true
  secretStoreRef:
    name: helmforge-fake-store
    kind: ClusterSecretStore
  data:
    - secretKey: appwrite-openssl-key
      remoteRef:
        key: test/token
    - secretKey: appwrite-jwt-secret
      remoteRef:
        key: test/token
