# SPDX-License-Identifier: Apache-2.0
architecture: replication

auth:
  enabled: true
  password: ci-valkey-password

tls:
  enabled: true
  existingSecret: valkey-tls

replication:
  primary:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
