# SPDX-License-Identifier: Apache-2.0
fullnameOverride: tei-eso
auth:
  existingSecret: tei-eso-api
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: tei-eso-api
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: api-key
            remoteRef:
              key: test/password
