# SPDX-License-Identifier: Apache-2.0
replicaCount: 1

auth:
  clientID: k3d-client
  clientSecret: k3d-client-secret
  cookieSecret: "0123456789abcdef0123456789abcdef"

config:
  provider: github
  redirectUrl: http://oauth2-proxy.localtest.me/oauth2/callback
  cookie:
    secure: false
  reverseProxy:
    enabled: true
    trustedProxyIps:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

metrics:
  enabled: true

pdb:
  enabled: false

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
