apiVersion: v2
name: kafka
description: Apache Kafka Helm chart for KRaft single-broker and production-oriented cluster topologies
type: application
version: 1.2.3
appVersion: "4.2.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - kafka
  - streaming
  - messaging
  - kraft
  - eventing
home: https://kafka.apache.org/
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/apache/kafka
icon: https://kafka.apache.org/images/apache-kafka.png
annotations:
  helmforge.dev/maturity: stable
  helmforge.dev/signed: cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: MIT
  artifacthub.io/category: streaming-messaging
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/kafka
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/kafka
