# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: glance-auth
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: glance-auth
      spec:
        secretStoreRef:
          name: platform-vault
          kind: ClusterSecretStore
        target:
          name: glance-auth
          creationPolicy: Owner
        data:
          - secretKey: password
            remoteRef:
              key: production/glance
              property: password
          - secretKey: secret-key
            remoteRef:
              key: production/glance
              property: secret-key

