{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.items | default list }}
{{- if not (dig "secretStoreRef" "name" "" (.spec | default dict)) }}
{{- fail "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled=true" }}
{{- end }}
{{- $secretStoreName := required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled=true" .spec.secretStoreRef.name }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.namedResource" (dict "root" $ "name" .name) }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
