{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.ingress.enabled }}
{{- $fullName := include "chart.serviceName" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "traefik" }}
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths | default (list "/") }}
          {{- if kindIs "string" . }}
          - path: {{ . }}
            pathType: Prefix
          {{- else }}
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
          {{- end }}
            backend:
              {{- if and (not (kindIs "string" .)) .backend }}
              {{- toYaml .backend | nindent 14 }}
              {{- else }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
