{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.sealedSecrets.enabled }}
{{- range .Values.sealedSecrets.items | default list }}
---
apiVersion: {{ .apiVersion | required "sealedSecrets.items[].apiVersion is required" }}
kind: SealedSecret
metadata:
  name: {{ include "chart.namedResource" (dict "root" $ "name" .name) }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
