# SPDX-License-Identifier: Apache-2.0
fullnameOverride: stirling-pdf
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: shared
          namespace: gateway-system
      hostnames:
        - pdf.example.test
