# SPDX-License-Identifier: Apache-2.0
fullnameOverride: stirling-pdf-metrics
persistence:
  size: 1Gi
metrics:
  enabled: true
  ingressFrom:
    - podSelector:
        matchLabels:
          app: stirling-pdf-monitor
  scrapeConfig:
    enabled: true
    apiKeySecret: stirling-metrics-key
    interval: 5s
    timeout: 5s
