{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "qdrant.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.extraEgress }}
    - Egress
    {{- end }}
  ingress:
    - from:
        {{- if .Values.networkPolicy.ingressFrom }}
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - protocol: TCP
          port: http
        - protocol: TCP
          port: grpc
    {{- if .Values.cluster.enabled }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "qdrant.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: p2p
    {{- end }}
  {{- with .Values.networkPolicy.extraEgress }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0
      ports:
        - protocol: TCP
          port: 443
    {{- if $.Values.cluster.enabled }}
    - to:
        - podSelector:
            matchLabels:
              {{- include "qdrant.selectorLabels" $ | nindent 14 }}
      ports:
        - protocol: TCP
          port: p2p
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
