# SPDX-License-Identifier: Apache-2.0
mode: distributed
replicaCount: 2
database:
  type: postgresql
storage:
  type: s3
  s3:
    bucket: attic-production
    endpoint: http://fixture-s3:9000
auth:
  generate: false
  existingSecret: attic-production
pdb:
  enabled: true
config:
  garbageCollection:
    enabled: false
