# SPDX-License-Identifier: Apache-2.0
externalSecrets:
  enabled: true
  items:
    - name: plugin
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          name: matterbridge-plugin
        data:
          - secretKey: MATTERBRIDGE_TEST_TOKEN
            remoteRef:
              key: test/token

extraEnvFrom:
  - secretRef:
      name: matterbridge-plugin
