# SPDX-License-Identifier: Apache-2.0
networkPolicy:
  enabled: true
  egress:
    enabled: true
    allowDNS: true
    extraEgress:
      - to:
          - ipBlock:
              cidr: 192.0.2.0/24
        ports:
          - protocol: TCP
            port: 1883
