{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $databaseMode := include "sonarqube.databaseMode" . -}}
{{- $needsDbSecret := and (eq $databaseMode "external") (not .Values.database.external.existingSecret) (not (and .Values.externalSecrets.enabled .Values.externalSecrets.database.enabled)) .Values.database.external.password -}}
{{- $needsMonitoringSecret := and .Values.sonarqube.monitoringPasscode (not .Values.sonarqube.existingMonitoringPasscodeSecret) (not (and .Values.externalSecrets.enabled .Values.externalSecrets.monitoringPasscode.enabled)) -}}
{{- if or $needsDbSecret $needsMonitoringSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube.secretName" . }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needsDbSecret }}
  {{ .Values.database.external.existingSecretPasswordKey }}: {{ .Values.database.external.password | quote }}
  {{- end }}
  {{- if $needsMonitoringSecret }}
  {{ .Values.sonarqube.existingMonitoringPasscodeSecretKey }}: {{ .Values.sonarqube.monitoringPasscode | quote }}
  {{- end }}
{{- end }}
