{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and (eq (include "netbird.databaseMode" .) "external") (not .Values.database.external.existingSecret) (not .Values.database.external.dsn) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.databasePasswordSecretName" . }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "netbird.databasePasswordSecretKey" . }}: {{ .Values.database.external.password | quote }}
{{- end }}
