{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.server.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.configSecretName" . }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    server:
      listenAddress: ":80"
      exposedAddress: {{ .Values.server.publicUrl | quote }}
      metricsPort: 9090
      healthcheckAddress: ":9000"
      logLevel: "info"
      logFile: "console"
      authSecret: {{ .Values.server.authSecret | quote }}
      dataDir: {{ printf "%s/" (.Values.persistence.mountPath | trimSuffix "/") | quote }}
      disableAnonymousMetrics: {{ .Values.server.disableAnonymousMetrics }}
      disableGeoliteUpdate: {{ .Values.server.disableGeoliteUpdate }}
      tls:
        certFile: ""
        keyFile: ""
        letsencrypt:
          enabled: false
          dataDir: ""
          domains: []
          email: ""
          awsRoute53: false
      auth:
        issuer: {{ .Values.server.auth.issuer | quote }}
        localAuthDisabled: {{ .Values.server.auth.localAuthDisabled }}
        signKeyRefreshEnabled: {{ .Values.server.auth.signKeyRefreshEnabled }}
        dashboardRedirectURIs:
          - {{ printf "%s/nb-auth" (.Values.server.publicUrl | trimSuffix "/") | quote }}
          - {{ printf "%s/nb-silent-auth" (.Values.server.publicUrl | trimSuffix "/") | quote }}
        cliRedirectURIs:
          - "http://localhost:53000/"
        {{- if or .Values.server.auth.owner.email .Values.server.auth.owner.password }}
        owner:
          email: {{ .Values.server.auth.owner.email | quote }}
          password: {{ .Values.server.auth.owner.password | quote }}
        {{- end }}
      store:
        engine: {{ include "netbird.storeEngine" . | quote }}
        dsn: {{ include "netbird.storeConfigDsn" . | quote }}
        encryptionKey: {{ .Values.server.store.encryptionKey | quote }}
{{- with .Values.server.config.extraYaml }}
{{ . | nindent 6 }}
{{- end }}
{{- end }}
