# SPDX-License-Identifier: Apache-2.0
fullnameOverride: dawarich-default
persistence:
  size: 2Gi
postgresql:
  standalone:
    persistence:
      size: 3Gi
redis:
  standalone:
    persistence:
      size: 1Gi
