# SPDX-License-Identifier: Apache-2.0
fullnameOverride: dawarich-eso
persistence:
  size: 2Gi
postgresql:
  standalone:
    persistence:
      size: 3Gi
redis:
  standalone:
    persistence:
      size: 1Gi
bootstrap:
  existingSecret: dawarich-eso-admin
identity:
  existingSecret: dawarich-eso-identity
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: dawarich-eso-admin
      spec:
        target:
          template:
            engineVersion: v2
            data:
              admin-password: '{{ .password | sha256sum | trunc 32 }}'
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
    - fullnameOverride: dawarich-eso-identity
      spec:
        target:
          template:
            engineVersion: v2
            data:
              SECRET_KEY_BASE: '{{ printf "SECRET_KEY_BASE:%s" .password | sha256sum }}'
              OTP_ENCRYPTION_PRIMARY_KEY: '{{ printf "OTP_ENCRYPTION_PRIMARY_KEY:%s" .password | sha256sum }}'
              OTP_ENCRYPTION_DETERMINISTIC_KEY: '{{ printf "OTP_ENCRYPTION_DETERMINISTIC_KEY:%s" .password | sha256sum }}'
              OTP_ENCRYPTION_KEY_DERIVATION_SALT: '{{ printf "OTP_ENCRYPTION_KEY_DERIVATION_SALT:%s" .password | sha256sum }}'
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        data:
          - secretKey: password
            remoteRef:
              key: test/password
