# SPDX-License-Identifier: Apache-2.0
persistence:
  size: 2Gi
postgresql:
  standalone:
    persistence:
      size: 3Gi
redis:
  standalone:
    persistence:
      size: 1Gi
fullnameOverride: dawarich-ingress
server:
  publicUrl: https://dawarich.example.test
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - host: dawarich.example.test
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dawarich-edge-tls
      hosts:
        - dawarich.example.test
