{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ include "clickhouse.namespace" . | quote }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: tcp
      port: {{ .Values.service.ports.tcp }}
      targetPort: tcp
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.headlessServiceName" . }}
  namespace: {{ include "clickhouse.namespace" . | quote }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.service.headless.publishNotReadyAddresses }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: tcp
      port: {{ .Values.service.ports.tcp }}
      targetPort: tcp
      protocol: TCP
    - name: interserver
      port: {{ .Values.service.ports.interserver }}
      targetPort: interserver
      protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
