# SPDX-License-Identifier: Apache-2.0
# CI scenario: explicit IP family fields on both DNS and web services (GR-058).
# The k3d validation lab is IPv4-only, so this scenario keeps rendering coverage
# without requiring IPv6 service allocation.
persistence:
  enabled: false

serviceDns:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4

serviceWeb:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
