# CI: external database
postgresql:
  enabled: false

redis:
  enabled: false

externalDatabase:
  enabled: true
  host: external-postgres.example.com
  port: 5432
  name: mhq-oss
  user: middleware
  password: "external-password"

externalRedis:
  enabled: true
  host: external-redis.example.com
  port: 6379
