docmost:
  appUrl: https://docmost.example.com

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: docmost.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: docmost-tls
      hosts:
        - docmost.example.com
