# SPDX-License-Identifier: Apache-2.0
database:
  type: postgresql
postgresql:
  enabled: true
  auth:
    database: atuin
    username: atuin
replicaCount: 2
podDisruptionBudget:
  enabled: true
metrics:
  enabled: true
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: atuin.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: atuin-tls
      hosts:
        - atuin.example.com
