mode: production

hostname:
  hostname: https://sso.example.com

database:
  external:
    host: postgresql.example.com
    password: change-me

networkPolicy:
  enabled: true
  egress:
    enabled: true
    databaseTo:
      - ipBlock:
          cidr: 10.10.0.0/16
    extraEgress:
      - to:
          - ipBlock:
              cidr: 10.20.0.0/16
        ports:
          - protocol: TCP
            port: 443
