# SPDX-License-Identifier: Apache-2.0
mode: production

hostname:
  hostname: https://sso.example.com

database:
  external:
    vendor: postgres
    host: postgresql.example.svc
    name: keycloak
    username: keycloak
    existingSecret: keycloak-db

capacity:
  profile: medium
priorityClassName: platform-critical
