architecture: cluster

auth:
  existingSecret: rabbitmq-auth

queueDefaults:
  type: quorum

cluster:
  replicaCount: 3
  persistence:
    enabled: true
    size: 20Gi

pdb:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
