{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.admin.existingSecret }}
{{- $secretName := include "pihole.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret $existingSecret.data }}
  password: {{ index $existingSecret.data "password" }}
  {{- else if .Values.admin.password }}
  password: {{ .Values.admin.password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 24 | b64enc }}
  {{- end }}
{{- end }}
