# SPDX-License-Identifier: Apache-2.0
# Cronicle with HTTPS ingress.
# Use case: internal scheduler exposed through a trusted ingress controller.

cronicle:
  baseUrl: https://cronicle.example.com
  emailFrom: cronicle@example.com
  maxJobs: 5

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: cronicle.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cronicle-tls
      hosts:
        - cronicle.example.com

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

