{{/* SPDX-License-Identifier: Apache-2.0 */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:
  server.yml: |
    {{- with .Values.ntfy.baseUrl }}
    base-url: {{ . | quote }}
    {{- end }}
    listen-http: ":80"
    cache-file: /var/cache/ntfy/cache.db
    auth-file: /var/cache/ntfy/auth.db
    auth-default-access: {{ .Values.ntfy.authDefaultAccess | quote }}
    behind-proxy: {{ .Values.ntfy.behindProxy }}
    {{- if .Values.ntfy.enableMetrics }}
    enable-metrics: true
    {{- with .Values.ntfy.metricsListenHttp }}
    metrics-listen-http: {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.ntfy.attachmentTotalSizeLimit }}
    attachment-total-size-limit: {{ . | quote }}
    {{- end }}
    {{- with .Values.ntfy.attachmentFileSizeLimit }}
    attachment-file-size-limit: {{ . | quote }}
    {{- end }}
    {{- with .Values.ntfy.attachmentExpiryDuration }}
    attachment-expiry-duration: {{ . | quote }}
    {{- end }}
    {{- with .Values.ntfy.extraConfig }}
    {{ . | nindent 4 }}
    {{- end }}
