apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karakeep.secretName" . }}
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
type: Opaque
data:
  nextauth-secret: {{ include "karakeep.nextAuthSecret" . | b64enc | quote }}
  meili-master-key: {{ include "karakeep.meiliMasterKey" . | b64enc | quote }}
