# SPDX-License-Identifier: Apache-2.0
# Private database/cache endpoints and existing credential Secrets are prerequisites.
postgresql:
  enabled: false
externalDatabase:
  host: postgres.database.svc.cluster.local
  database: nextcloud
  username: nextcloud
  existingSecret: nextcloud-external-database
redis:
  enabled: false
externalRedis:
  host: redis.cache.svc.cluster.local
  existingSecret: nextcloud-external-redis
