# SPDX-License-Identifier: Apache-2.0
# CI: external PostgreSQL database
postgresql:
  enabled: false

database:
  external:
    host: db.example.com
    port: "5432"
    name: metabase
    username: metabase_user
    password: "ci-password"
