# SPDX-License-Identifier: Apache-2.0
# CI scenario: External Secrets Operator (GR-061).
# metabase.existingSecret is required when externalSecrets.enabled=true
# to prevent credential drift with the chart-managed app Secret.
postgresql:
  enabled: false

database:
  external:
    host: "postgres.example.com"
    name: metabase
    username: metabase
    existingSecret: my-metabase-db-secret

metabase:
  existingSecret: my-metabase-app-secret

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: encryption-secret-key
      remoteRef:
        key: metabase/credentials
        property: encryption-secret-key
