# SPDX-License-Identifier: Apache-2.0
fullnameOverride: ghostfolio
postgresql:
  enabled: false
database:
  external:
    enabled: true
    host: ghostfolio-external-postgresql
    existingSecret: ghostfolio-external-database
redis:
  enabled: false
  external:
    enabled: true
    host: ghostfolio-external-redis
    existingSecret: ghostfolio-external-redis
networkPolicy:
  extraEgress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ghostfolio-external-postgresql
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ghostfolio-external-redis
      ports:
        - protocol: TCP
          port: 6379
