# SPDX-License-Identifier: Apache-2.0
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: matterbridge.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: matterbridge-ingress-tls
      hosts:
        - matterbridge.example.com
