# SPDX-License-Identifier: Apache-2.0
# Typical LAN deployment. Label one trusted node before applying this file.
network:
  hostNetwork: true

nodeSelector:
  matterbridge.helmforge.dev/lan-node: "true"

persistence:
  size: 5Gi
  storageClass: fast-retained

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

matterbridge:
  logger: info
  matterLogger: notice
