# SPDX-License-Identifier: Apache-2.0
database:
  mode: external
  external:
    host: postgresql.example.internal
    existingSecret: nautilus-database
messageBus:
  mode: external
  external:
    host: redis.example.internal
    existingSecret: nautilus-redis
secrets:
  existingSecret: nautilus-venue
