{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and (eq (include "matomo.databaseMode" .) "external") (not .Values.database.external.existingSecret) (not .Values.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.databaseSecretName" . }}
  namespace: {{ include "matomo.namespace" . | quote }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.database.external.password | quote }}
{{- end }}
