# SPDX-License-Identifier: Apache-2.0
proxy:
  existingSecret: jupyterhub-proxy-token

externalSecrets:
  enabled: true
  secretStoreRef:
    name: platform-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: proxy-token
      remoteRef:
        key: jupyterhub/proxy
        property: proxy-token
