# SPDX-License-Identifier: Apache-2.0
{{- if and (eq (include "phpmyadmin.needsConfigMount" .) "true") (not .Values.config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phpmyadmin.configMapName" . }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
data:
  config.user.inc.php: |
    {{- if eq (include "phpmyadmin.needsGeneratedConfig" .) "true" }}
    {{- include "phpmyadmin.generatedConfig" . | nindent 4 }}
    {{- end }}
    {{- if .Values.config.customConfig }}
    {{- .Values.config.customConfig | nindent 4 }}
    {{- end }}
{{- end }}
