# SPDX-License-Identifier: Apache-2.0
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "phpmyadmin.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
{{- end }}
