# SPDX-License-Identifier: Apache-2.0
{{- if and (or .Values.auth.password .Values.auth.blowfishSecret .Values.phpmyadmin.controlPassword) (not .Values.auth.existingSecret) (not .Values.externalSecrets.auth.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phpmyadmin.authSecretName" . }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.username }}
  {{ .Values.auth.existingSecretUsernameKey }}: {{ .Values.auth.username | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  {{ .Values.auth.existingSecretPasswordKey }}: {{ .Values.auth.password | quote }}
  {{- end }}
  {{- if .Values.auth.blowfishSecret }}
  {{ .Values.auth.existingSecretBlowfishKey }}: {{ .Values.auth.blowfishSecret | quote }}
  {{- end }}
  {{- if .Values.phpmyadmin.controlPassword }}
  {{ .Values.auth.existingSecretControlPasswordKey }}: {{ .Values.phpmyadmin.controlPassword | quote }}
  {{- end }}
{{- end }}
