# SPDX-License-Identifier: Apache-2.0
# CI scenario: External Secrets Operator integration (GR-061)
# Renders the ExternalSecret manifest for backup S3 credentials
backup:
  enabled: true
  suspend: true
  s3:
    endpoint: https://s3.example.com
    bucket: komga-backup
    existingSecret: komga-ci-external-secrets-komga-backup-s3

externalSecrets:
  enabled: true
  items:
    - name: backup-s3
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          name: komga-ci-external-secrets-komga-backup-s3
          creationPolicy: Owner
        data:
          - secretKey: access-key
            remoteRef:
              key: test/username
          - secretKey: secret-key
            remoteRef:
              key: test/password
