# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)

admin:
  existingSecret: vaultwarden-credentials

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: admin-token
      remoteRef:
        key: vaultwarden/auth
        property: token
