# SPDX-License-Identifier: Apache-2.0
data:
  persistence:
    enabled: true
    selectorLabels:
      restore-id: vaultwarden-prod-restore

nodeSelector:
  kubernetes.io/hostname: k3d-helmforge-tests-wsl-server-0
