{{- if not .Values.appwrite.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appwrite.fullname" . }}-secret
  labels:
    {{- include "appwrite.labels" . | nindent 4 }}
type: Opaque
data:
  appwrite-openssl-key: {{ (.Values.appwrite.openSslKeyV1 | default (randAlphaNum 64 | sha256sum | trunc 64)) | b64enc | quote }}
  appwrite-jwt-secret: {{ (randAlphaNum 128) | b64enc | quote }}
  {{- if and .Values.appwrite.smtp.host .Values.appwrite.smtp.password (not .Values.appwrite.smtp.existingSecret) }}
  smtp-password: {{ .Values.appwrite.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and (eq (include "appwrite.databaseMode" .) "external") (not .Values.database.external.existingSecret) .Values.database.external.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appwrite.fullname" . }}-database
  labels:
    {{- include "appwrite.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.database.external.rootPassword | b64enc | quote }}
{{- end }}
{{- if and (eq (include "appwrite.cacheMode" .) "external") (not .Values.cache.external.existingSecret) .Values.cache.external.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appwrite.fullname" . }}-redis
  labels:
    {{- include "appwrite.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.cache.external.password | b64enc | quote }}
{{- end }}
