{{- if not .Values.ckan.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.fullname" . }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
type: Opaque
stringData:
  sysadmin-password: {{ .Values.ckan.sysadminPassword | default (randAlphaNum 32) | quote }}
  session-secret: {{ .Values.ckan.sessionSecret | default (randAlphaNum 42) | quote }}
  jwt-secret: {{ .Values.ckan.jwtSecret | default (randAlphaNum 42) | quote }}
{{- end }}
---
{{- if and (eq .Values.database.mode "external") (not .Values.database.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database" (include "ckan.fullname" .) }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.database.external.password | default (randAlphaNum 32) | quote }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backup" (include "ckan.fullname" .) }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.backup.s3.accessKey | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
