# SPDX-License-Identifier: Apache-2.0
# CI scenario: dual-stack for HTTP service (GR-058)
mongodb:
  enabled: false

externalMongodb:
  enabled: true
  uri: mongodb://external-mongo:27017/countly

service:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
