# SPDX-License-Identifier: Apache-2.0
# CI: external MongoDB, backed by the bundled MongoDB service for k3d.
mongodb:
  enabled: true
  auth:
    rootPassword: test-password

externalMongodb:
  enabled: true
  uri: "mongodb://root:test-password@countly-external-mongodb:27017/countly?authSource=admin"

extraManifests:
  - apiVersion: v1
    kind: Service
    metadata:
      name: countly-external-mongodb
    spec:
      type: ClusterIP
      ports:
        - name: mongodb
          port: 27017
          targetPort: mongodb
      selector:
        app.kubernetes.io/name: mongodb
        app.kubernetes.io/component: mongodb
