# SPDX-License-Identifier: Apache-2.0
# CI scenario: ExternalSecrets with drift guard (GR-061)
mongodb:
  enabled: false

externalMongodb:
  enabled: true
  existingSecret: countly-mongo-credentials
  existingSecretUriKey: mongodb-uri

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: mongodb-uri
      remoteRef:
        key: countly/db
        property: uri
