apiVersion: v2
name: phpmyadmin
type: application
version: 1.0.7
appVersion: "5.2.3"
kubeVersion: ">=1.26.0-0"
description: A Helm chart for deploying phpMyAdmin on Kubernetes as a web-based MySQL/MariaDB administration tool
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - phpmyadmin
  - mysql
  - mariadb
  - database
  - admin
  - web-ui
home: https://www.phpmyadmin.net
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/r/phpmyadmin/phpmyadmin
  - https://github.com/phpmyadmin/phpmyadmin
icon: https://helmforge.dev/icons/charts/phpmyadmin.png
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: database
  helmforge.dev/maturity: stable
  helmforge.dev/signed: cosign
  artifacthub.io/signKey: |
    fingerprint: 6748042FBAD8C2E11C65E564170D55148EB88A9D
    url: https://repo.helmforge.dev/pgp-public-key.asc
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/phpmyadmin
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/phpmyadmin
    - name: support
      url: https://github.com/helmforgedev/charts/issues
  artifacthub.io/images: |
    - name: phpmyadmin
      image: docker.io/phpmyadmin/phpmyadmin:5.2.3
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/helmforge/mysql
    - url: https://artifacthub.io/packages/helm/helmforge/mariadb
