# SPDX-License-Identifier: Apache-2.0
externalSecrets:
  enabled: true
  items:
    - name: strava
      storeRef:
        name: platform-secrets
        kind: ClusterSecretStore
      targetName: strava-credentials
      data:
        - secretKey: client-id
          remoteRef:
            key: strava/oauth
            property: client-id
        - secretKey: client-secret
          remoteRef:
            key: strava/oauth
            property: client-secret
        - secretKey: refresh-token
          remoteRef:
            key: strava/oauth
            property: refresh-token

strava:
  existingSecret: strava-credentials
