# SPDX-License-Identifier: Apache-2.0
gatewayAPI:
  enabled: true
  httpRoutes:
    - name: web
      parentRefs:
        - name: public
          namespace: gateway-system
      hostnames:
        - strava.example.com
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /

strava:
  config: |
    general:
      appUrl: "https://strava.example.com/"

