# SPDX-License-Identifier: Apache-2.0
strava:
  clientId: "12345"
  clientSecret: "change-me"
  refreshToken: "change-me"
  config: |
    general:
      appUrl: "http://localhost:8080/"

persistence:
  enabled: true
  size: 2Gi

