# SPDX-License-Identifier: Apache-2.0
architecture: sentinel

auth:
  enabled: true
  password: ci-redis-password

node:
  replicaCount: 3

sentinel:
  replicaCount: 3
  masterSet: ci-master
  quorum: 2

pdb:
  enabled: true
