# SPDX-License-Identifier: Apache-2.0
# Layer on the production HTTPS and encryption Secret configuration.
database:
  type: postgresql
postgresql:
  enabled: true
  auth:
    database: pocketid
    username: pocketid
    existingSecret: pocket-id-postgresql-auth
  standalone:
    persistence:
      size: 20Gi
