# SPDX-License-Identifier: Apache-2.0
# Layer on the production HTTPS and encryption Secret configuration.
database:
  type: postgresql
  host: postgresql.database.svc.cluster.local
  name: pocketid
  username: pocketid
  passwordSecret: pocket-id-external-postgresql
  sslMode: verify-full
  caSecret: database-ca
postgresql:
  enabled: false
networkPolicy:
  extraEgress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
