# SPDX-License-Identifier: Apache-2.0
# BookLore with Gateway API exposure.
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: gateway-system
      hostnames:
        - books.example.com
