# SPDX-License-Identifier: Apache-2.0
# CI scenario: External Secrets Operator (GR-061).
# secrets.existingSecret is required when externalSecrets.enabled=true.
persistence:
  enabled: false

secrets:
  existingSecret: my-authelia-secrets

externalSecrets:
  enabled: true
  secretStoreRef:
    name: my-store
    kind: ClusterSecretStore
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: authelia/secrets
        property: jwt-secret
    - secretKey: session-secret
      remoteRef:
        key: authelia/secrets
        property: session-secret
    - secretKey: storage-encryption-key
      remoteRef:
        key: authelia/secrets
        property: storage-encryption-key
