{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.secrets.generate (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulwark-mail.fullname" . }}
  labels:
    {{- include "bulwark-mail.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.sessionSecret }}: {{ include "bulwark-mail.sessionSecret" . | quote }}
  {{- with .Values.secrets.adminPassword }}
  {{ $.Values.secrets.keys.adminPassword }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.oauthClientSecret }}
  {{ $.Values.secrets.keys.oauthClientSecret }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.jwtAuthSecret }}
  {{ $.Values.secrets.keys.jwtAuthSecret }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.stalwartMasterUser }}
  {{ $.Values.secrets.keys.stalwartMasterUser }}: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.stalwartMasterPassword }}
  {{ $.Values.secrets.keys.stalwartMasterPassword }}: {{ . | quote }}
  {{- end }}
{{- end }}
