{{- if not .Values.openWebui.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-app" (include "open-webui.fullname" .) }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  secret-key: {{ .Values.openWebui.secretKey | default (randAlphaNum 64) | quote }}
  {{- if .Values.openWebui.openaiApiKey }}
  openai-api-key: {{ .Values.openWebui.openaiApiKey | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backup" (include "open-webui.fullname" .) }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.backup.s3.accessKey | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | quote }}
{{- end }}
