# SPDX-License-Identifier: Apache-2.0
auth:
  dummyPassword: helmforge
hub:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
proxy:
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi
