# SPDX-License-Identifier: Apache-2.0
pdb:
  enabled: true
singleuser:
  storage:
    enabled: true
    capacity: 1Gi
networkPolicy:
  enabled: true
proxy:
  existingSecret: jupyterhub-proxy-token
extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: jupyterhub-proxy-token
    type: Opaque
    stringData:
      proxy-token: helmforge-test-token
auth:
  type: custom
hub:
  extraConfig: |
    c.JupyterHub.authenticator_class = "nativeauthenticator.NativeAuthenticator"
