{{- if .Values.backup.enabled }}
{{- $_ := include "drupal.backupEnabled" . }}
{{- if not .Values.backup.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.backupSecretName" . }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
data:
  access-key: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | b64enc | quote }}
{{- end }}
{{- if and (.Values.backup.database.password) (not .Values.backup.database.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.backupDatabasePasswordSecretName" . }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
data:
  database-password: {{ .Values.backup.database.password | b64enc | quote }}
{{- end }}
{{- end }}
