{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "hermes-agent.validate" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-agent.fullname" . }}-config
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "hermes-agent.config" . | nindent 4 }}
  SOUL.md: {{ .Values.config.soul | quote }}
  bootstrap.py: |
    {{- .Files.Get "files/bootstrap.py" | nindent 4 }}
  health.py: |
    {{- .Files.Get "files/health.py" | nindent 4 }}
  entrypoint.py: |
    {{- .Files.Get "files/entrypoint.py" | nindent 4 }}
