# SPDX-License-Identifier: Apache-2.0
---
auth:
  existingSecret: pimcore-application
externalSecrets:
  enabled: true
  items:
    - name: application
      spec:
        secretStoreRef:
          name: helmforge-fake-store
          kind: ClusterSecretStore
        target:
          name: pimcore-application
          creationPolicy: Owner
          template:
            data:
              application-secret: "{{ .token }}-{{ .token }}-{{ .token }}"
              admin-password: "{{ .password }}"
              product-key: ""
              instance-identifier: ""
              encryption-secret: ""
              mercure-jwt-key: "{{ .token }}-{{ .token }}-{{ .token }}"
        data:
          - secretKey: token
            remoteRef:
              key: test/token
          - secretKey: password
            remoteRef:
              key: test/password
