# SPDX-License-Identifier: Apache-2.0
---
mariadb:
  enabled: true
rabbitmq:
  enabled: true
redis:
  enabled: true
database:
  mode: external
  external:
    host: pimcore-ci-external-services-values-mariadb
    existingSecret: pimcore-ci-external-services-values-mariadb-auth
    existingSecretPasswordKey: mariadb-user-password
queue:
  mode: external
  external:
    host: pimcore-ci-external-services-values-rabbitmq
    username: pimcore
    existingSecret: pimcore-ci-external-services-values-rabbitmq-auth
    existingSecretPasswordKey: rabbitmq-password
cache:
  enabled: true
  mode: external
  external:
    host: pimcore-ci-external-services-values-redis-client
    existingSecret: pimcore-ci-external-services-values-redis-auth
    existingSecretPasswordKey: redis-password
