# SPDX-License-Identifier: Apache-2.0
# Simple Komga deployment with defaults (SQLite + persistent storage)
persistence:
  config:
    enabled: true
    size: 2Gi
  data:
    enabled: true
    size: 100Gi
