auth:
  enabled: true
  password: test-password

acl:
  enabled: true
  rules: |
    topic readwrite #

broker:
  tls:
    enabled: true
    certSecretName: mosquitto-tls
    caFile: ca.crt
    requireCertificate: true
    useIdentityAsUsername: true

service:
  type: LoadBalancer
