architecture: replication

auth:
  rootPassword: "change-me"
  database: myapp
  username: myapp
  password: "change-me"
  replicationPassword: "change-me"

replication:
  source:
    persistence:
      enabled: true
      size: 50Gi
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      size: 50Gi
