# SPDX-License-Identifier: Apache-2.0
# Compatibility Service that points consumers to an externally hosted OpenReel Video endpoint

service:
  type: ExternalName
  externalName: openreel-static.example.com

ingress:
  enabled: false

gateway:
  enabled: false
