apiVersion: v2
name: redis
description: Redis Helm Chart for standalone, replication, sentinel, and cluster topologies
type: application
version: 1.5.1
appVersion: "8.6.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - redis
  - cache
  - datastore
  - sentinel
  - cluster
home: https://redis.io
sources:
  - https://github.com/helmforgedev/charts
  - https://hub.docker.com/_/redis
icon: https://raw.githubusercontent.com/docker-library/docs/master/redis/logo.png
annotations:
  helmforge.dev/maturity: stable
  helmforge.dev/signed: cosign
  artifacthub.io/license: MIT
  artifacthub.io/category: database
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/redis
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/redis
