{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.moodle.existingSecret }}
{{- $name := include "moodle.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $password := .Values.moodle.adminPassword }}
{{- if and (not $password) $existing }}
{{- $password = index $existing.data .Values.moodle.existingSecretPasswordKey | b64dec }}
{{- end }}
{{- if not $password }}{{- $password = printf "Aa1!%s" (randAlphaNum 28) }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "moodle.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.moodle.existingSecretPasswordKey }}: {{ $password | b64enc | quote }}
{{- end }}
