# SPDX-License-Identifier: Apache-2.0
auth:
  existingSecret: siyuan-auth
externalSecrets:
  enabled: true
  items:
    - fullnameOverride: siyuan-auth
      spec:
        secretStoreRef:
          name: production
          kind: ClusterSecretStore
        data:
          - secretKey: access-code
            remoteRef:
              key: applications/siyuan/access-code
