apiVersion: v2
name: guacamole
description: Apache Guacamole clientless remote desktop gateway with guacd, PostgreSQL or MySQL, OIDC/SAML SSO, and S3 backup
type: application
version: 1.3.3
appVersion: "1.6.0"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - guacamole
  - remote-desktop
  - rdp
  - vnc
  - ssh
  - gateway
  - oidc
  - saml
home: https://guacamole.apache.org
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/apache/guacamole-server
  - https://github.com/apache/guacamole-client
icon: https://raw.githubusercontent.com/apache/guacamole-website/main/images/logos/guac-classic-logo.svg
annotations:
  helmforge.dev/maturity: stable
  helmforge.dev/signed: cosign
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: MIT
  artifacthub.io/category: networking
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/guacamole
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/guacamole
dependencies:
  - name: postgresql
    version: 1.8.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: postgresql.enabled
  - name: mysql
    version: 1.7.1
    repository: oci://ghcr.io/helmforgedev/helm
    condition: mysql.enabled
