{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.pdb.enabled (eq .Values.mode "distributed") (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "attic.fullname" . }}
  labels:
    {{- include "attic.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "attic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
{{- end }}
