{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretRootPasswordKey }}: {{ include "mysql.rootPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretUserPasswordKey }}: {{ include "mysql.userPassword" . | b64enc | quote }}
  {{ .Values.auth.existingSecretReplicationPasswordKey }}: {{ include "mysql.replicationPassword" . | b64enc | quote }}
{{- end }}
