# SPDX-License-Identifier: Apache-2.0
ingress:
  enabled: true
  hosts:
    - host: atuin.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: atuin-tls
      hosts:
        - atuin.example.com
