# SPDX-License-Identifier: Apache-2.0
fullnameOverride: opencloud-gateway-api
gatewayAPI:
  enabled: true
  httpRoutes:
    - parentRefs:
        - name: shared
          namespace: gateway-system
      hostnames:
        - files.example.test
persistence:
  size: 1Gi
