{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langflow.fullname" . }}
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "langflow.selectorLabels" . | nindent 6 }}
{{- end }}
