{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and (not .Values.auth.existingSecret) (or .Values.auth.secretKey .Values.auth.superuser .Values.auth.superuserPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow.fullname" . }}
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.secretKey }}
  {{ .Values.auth.secretKeyKey }}: {{ .Values.auth.secretKey | quote }}
  {{- end }}
  {{- if .Values.auth.superuser }}
  {{ .Values.auth.superuserKey }}: {{ .Values.auth.superuser | quote }}
  {{- end }}
  {{- if .Values.auth.superuserPassword }}
  {{ .Values.auth.superuserPasswordKey }}: {{ .Values.auth.superuserPassword | quote }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.database.existingSecret) .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langflow.fullname" . }}-database
  labels:
    {{- include "langflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.urlKey }}: {{ .Values.database.url | quote }}
{{- end }}
