{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- include "mssql.validate" . }}
{{- if .Values.license.acceptEULA }}
{{- $credentials := include "mssql.credentials" . | fromJson }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.authSecret" . }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $credentials }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if not .Values.tls.existingSecret }}
{{- $old := lookup "v1" "Secret" .Release.Namespace (include "mssql.tlsSecret" .) }}
{{- $data := dict }}
{{- if $old }}
{{- $data = $old.data }}
{{- else }}
{{- $ca := genCA (printf "%s-ca" (include "mssql.fullname" .)) (int .Values.tls.durationDays) }}
{{- $name := include "mssql.fullname" . }}
{{- $names := concat (list $name (printf "%s.%s" $name .Release.Namespace) (printf "%s.%s.svc" $name .Release.Namespace) (printf "%s.%s.svc.cluster.local" $name .Release.Namespace) "localhost") .Values.tls.extraDnsNames }}
{{- $cert := genSignedCert $name (list "127.0.0.1" "::1") $names (int .Values.tls.durationDays) $ca }}
{{- $_ := set $data "tls.crt" ($cert.Cert | b64enc) }}{{- $_ := set $data "tls.key" ($cert.Key | b64enc) }}{{- $_ := set $data "ca.crt" ($ca.Cert | b64enc) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.tlsSecret" . }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- toYaml $data | nindent 2 }}
{{- end }}
{{- if and .Values.metrics.enabled (not .Values.metrics.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql.fullname" . }}-metrics
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.metrics.secretKey | default "dsn" | quote }}: {{ printf "sqlserver://hf_metrics:%s@%s:%v?database=master&encrypt=true&TrustServerCertificate=false&certificate=/tls/ca.pem" (index $credentials "metrics-password" | urlquery) (include "mssql.fullname" .) .Values.service.port | quote }}
{{- end }}
{{- end }}
