{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.github.personalAccessToken (not .Values.github.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-mcp-server.fullname" . }}
type: Opaque
stringData:
  token: {{ .Values.github.personalAccessToken | quote }}
{{- end }}
