{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.github.personalAccessToken (not .Values.github.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-mcp-server.fullname" . }}
  labels:
    {{- include "github-mcp-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.github.existingSecretKey }}: {{ .Values.github.personalAccessToken | quote }}
{{- end }}
