apiVersion: v2
name: rabbitmq
description: RabbitMQ for Kubernetes with explicit single-node and cluster modes
type: application
version: 1.4.3
appVersion: "4.2.4"
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: helmforgedev
  - name: mberlofa
keywords:
  - rabbitmq
  - amqp
  - messaging
  - queue
  - cluster
home: https://www.rabbitmq.com/
sources:
  - https://github.com/helmforgedev/charts
  - https://github.com/docker-library/rabbitmq
icon: https://raw.githubusercontent.com/rabbitmq/rabbitmq-website/main/static/img/rabbitmq-logo.svg
annotations:
  helmforge.dev/maturity: stable
  helmforge.dev/signed: cosign
  helmforge.dev/repository: https://repo.helmforge.dev
  artifacthub.io/license: MIT
  artifacthub.io/category: streaming-messaging
  artifacthub.io/links: |
    - name: Documentation
      url: https://helmforge.dev/docs/charts/rabbitmq
    - name: Source
      url: https://github.com/helmforgedev/charts/tree/main/charts/rabbitmq
