{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if not .Values.strava.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-strava" (include "strava-statistics.fullname" .) }}
  labels:
    {{- include "strava-statistics.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.strava.clientId | quote }}
  client-secret: {{ .Values.strava.clientSecret | quote }}
  refresh-token: {{ .Values.strava.refreshToken | quote }}
{{- end }}
