{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "umami.fullname" . }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
spec:
  {{- if ne (toString .Values.pdb.maxUnavailable) "" }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "umami.componentLabels" . | nindent 6 }}
{{- end }}
