# SPDX-License-Identifier: Apache-2.0
# Use only after validating the provider's Gateway API version and channel.
crds:
  gatewayAPI:
    enabled: false
  envoyGateway:
    enabled: true
safeUpgradePolicy:
  management: external
