{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.admin.create (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.adminSecretName" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.admin.existingSecretUserKey }}: {{ include "jenkins.adminUser" . | quote }}
  {{ .Values.admin.existingSecretPasswordKey }}: {{ include "jenkins.adminPassword" . | quote }}
{{- end }}
